### ISSUE TITLE
Improve F# signature formatting

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/FSharp.Formatting#106]
Take the following signature:

```
Signature: (untypedParse:ParseFileResults * filename * source * options * isResultObsolete * textSnapshotInfo:obj option) -> Async<CheckFileOption>
```

Once it gets to a certain width it becomes hard to read especially if it is forced to break lines in the middle.  Perhaps some formatting like this might be nice:

![screen shot 2014-01-21 at 09 57 44](https://f.cloud.github.com/assets/588746/1962222/b80a00c0-8283-11e3-81a1-9cd6c660edf8.png)

colourising type names and the `->` could also improve legibility

**Comment by dsyme** [comment]
This is fixed for now
