### ISSUE TITLE
The end line of github links is not right

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/FSharp.Formatting#154]
Example: in http://fsharp.github.io/FSharp.Data/reference/fsharp-data-jsonvalue.html, The link for RequestAsync is https://github.com/fsharp/FSharp.Data/tree/master//src/Json/JsonValue.fs#L332-332, but it should instead be https://github.com/fsharp/FSharp.Data/tree/master/src/Json/JsonValue.fs#L332-344 (note there was also an extra /)

**Comment by ovatsus** [comment]
Still repros on latest version

**Comment by matthid** [comment]
You can fix this by adding '/' to the end of https://github.com/fsharp/FSharp.Data/blob/master/docs/tools/generate.fsx#L90, but I agree that F# Formatting could handle this as well.

**Comment by ovatsus** [comment]
What about the line numbers? Any idea?

**Comment by matthid** [comment]
You want the complete function or what's the problem? I think FCS just gives the lines of the declaration without the body, so if you want this particular feature you should look if they have an API for this and if not open an issue over there.

**Comment by ovatsus** [comment]
I think this worked in the past and then was broken

**Comment by matthid** [comment]
Interesting, I always thought this is how it is :). I'm pretty sure FCS broke it as we just return what FCS gives us here at F# formatting. So you should try to get a standalone repro and open an issue there. Do you happen to remember which version worked (could be helpful to check if it still works with an old FCS version).

**Comment by tpetricek** [comment]
cc @enricosada @dsyme @vasily-kirichenko @dungpa - just in case they recall some potentially related change (that would break reported line numbers) in F# Compiler Service.

**Comment by dsyme** [comment]
Closing this old issue
