### ISSUE TITLE
A value with surround ticks and comma is not parsed correctly in special command

### ISSUE THREAD

**Issue by kimsk** [fsprojects/FSharp.Formatting#165]
For example, I have something like this in a F# script file (*.fsx).

```
let ``P(R,C)`` = 10
(*** include-value:``P(R,C)`` ***)
```

The ValueReference is `P(R` instead of `(R,C)`

![image](https://cloud.githubusercontent.com/assets/116863/2952849/b96f9e60-da45-11e3-80c6-2189b7afa376.png)

**Comment by dsyme** [comment]
This is not supported nor do I think we should support it
