### ISSUE TITLE
Need to catch all throws for good error reporting

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Formatting#196]
This is a real problem when attempting to automate looping through folders to generate docs on a whole system. 

In particular is is possible to throw inside compiler services, in which case no useful information is returned on which token, line, or even file caused the problem.

Need to catch all errors and minimally report the offending file, better yet, line number and token as well.

(I started looking at this, but unfortunately do not have time to continue for the foreseeable future, so I am recording it here.)

**Comment by dsyme** [comment]
The error reporting now shows many more errors
