### ISSUE TITLE
Simplify literate documentation examples in FSharp.Formatting 

### ISSUE THREAD

**Issue by ToJans** [fsprojects/FSharp.Formatting#248]
## Problem

When writing F# inline documentation examples there's a lot of protocol because you need to close the comment and use things like `(*** [some metadata] ***)` and reopen the comment again...
## Inspiration

In Elixir writing documentation examples is a breeze, because they use standard markdown code to include snippets, which can get tested when you build your documentation. 
This allows a very succinct type of code documentation, where the examples always work.
## An example

After looking at the current approach F# uses and comparing this with my Elixir background, I created a small mock-up that would show what my (personal) ideal approach for documenting would look like.

The F# code would look like this:

`````` F#
    (** Sums a list of integers.

    ## Remarks

    - Produces an `ArgumentException` for an empty list. 
    - It would be better if we'd use `List.fold` with a `0`, so it doesn't throw upon an empty list.

    ## Examples

    ```
    > let somelist = [1;2;3;4];;
    > listsum somelist;;
    val it : int = 10 
    > listsum [];;
    System.ArgumentException...
    > listsum [4;5];;
    val it : int = 9
    ```
    *)
    let listsum = List.reduce (+)
``````
## Documentation extraction

This would be fairly standard markdown, with the exception of maybe adding the function header & type by default; it generate something like this:

`-------------------------------><8--------------------------`
## listsum:: int list -> int

Sums a list of integers.
## Remarks
- Produces an `ArgumentException` for an empty list. 
- It would be better if we'd use `List.fold` with a `0`, so it doesn't throw upon an empty list.
# Examples

``` F#
> let somelist = [1;2;3;4];;
> listsum somelist;;
val it : int = 10
> listsum [];;
System.ArgumentException...
> listsum [4;5];;
val it : int = 9
```

`-------------------------------><8--------------------------`
## Verification of the examples during the build of the documentation

Here's how the testing of the examples would go:
In a codeblock:
- If the source line starts with `>`:
  - execute it and store the output lines
  - If a source line doesn't start with `>`:
    - If the source line ends with `...` compare everything in front of it with the current output line
    - If it doesn't, compare the source line with the current output line
  - go to the next output line & source line
## Mentioned disadvantage

When discussing this approach on twitter, the lack of not having intellisense in your examples was mentioned. As I found out during my time with Elixir, that shouldn't really be an issue, because you usually write your examples in the REPL anyway so you can verify them, so it's just a simple copy and paste.

**Comment by tpetricek** [comment]
I like the idea, but I currently don't have the capacity to work on this myself, so I marked it as up-for-grabs.

One thing to note is that this would probably be easier using the `///` style of comments (because those are extracted by the F# compiler). So, the snippets would look more like:

    /// Sums a list of integers.
    /// ## Remarks
    /// 
    /// - Produces an `ArgumentException` for an empty list. 
    /// - It would be better if we'd use `List.fold` with a `0`, so it doesn't throw upon an empty list.
    /// 
    /// ## Examples
    /// 
    /// ```
    /// > let somelist = [1;2;3;4];;
    /// > listsum somelist;;
    /// val it : int = 10 
    /// > listsum [];;
    /// System.ArgumentException...
    /// > listsum [4;5];;
    /// val it : int = 9
    /// ```
    /// 
    let listsum = List.reduce (+)

If this is to be used for library documentation, then I think it would be a transformation done in the MetadataFormat project (which currently extracts information about modules & functions and gets the associated comments for them).

**Comment by ToJans** [comment]
Sounds good!
