### ISSUE TITLE
Add CSS for subpages in menu

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Formatting#264]
![image](https://cloud.githubusercontent.com/assets/57396/6254307/e86e785e-b7a7-11e4-9df1-f7b0506ea951.png)

would be nice to have a CSS magic to make this pretty

**Comment by tpetricek** [comment]
I did this in Deedle docs (see [the menu on the right here](http://bluemountaincapital.github.io/Deedle/series.html)) and is certainly a nice thing to do (although Deedle does this by having [conditional in the template](https://github.com/BlueMountainCapital/Deedle/blob/master/docs/tools/templates/template.cshtml#L74)).

Not sure how to do this with CSS magic. One thing I found in Deedle is that my headings in the docs are usually too long, so I tend to write a different shorter thing in the menu... 

But getting this for free would be nice!

**Comment by dsyme** [comment]
This is a matter for the user template
