### ISSUE TITLE
Crash when no associated xml file

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FSharp.Formatting#290]
When a project doesn't generate an xml file on build, this will result in a crash when trying to generate reference docs:

```
System.IO.FileNotFoundException: Associated XML file
```

So, for example, in a multi-project solution, this will fail when you would like to leave out some projects from creating references. Is this the desired behavior?

**Comment by tpetricek** [comment]
I think calling the library with a DLL file that has no associated XML could be treated as an invalid operation (when someone does that, they are probably not doing that intentionally.... and I guess that silently ignoring this might be more confusing than throwing..)

That said, the recent change in ProjectScaffold (see discussion here https://github.com/fsprojects/ProjectScaffold/pull/153) makes it harder to explicitly specify DLLs you want to process. So I'm not sure what to do. Perhaps @Vidarls has some thoughts? (Should we add black-listing to ProjectScaffold, or should we silently ignore this (perhaps with a log...)?)

**Comment by forki** [comment]
I'm voting to ignore and trace a warning

2015-04-10 13:24 GMT+02:00 Tomas Petricek <notifications@github.com>:

**Comment by tpetricek** [comment]
Thanks for the vote @forki! 

The `MetadataFormat.Generate` method has two overloads. One taking _list_ of DLLs and one taking a _single_ DLL. Perhaps it would make sense to ignore this when we get list, but throw when it is called on just a single DLL?

Or is that just making the behavior uselessly complicated?

**Comment by matthid** [comment]
I think we should handle this in ProjectScaffold and not in FSharp.Formatting. I expect an exception when I tell FSharp.Formatting to process something it can't handle.

**Comment by tpetricek** [comment]
Looks like we have no clear decision here. Would my above proposal make sense:

> Add an optional parameter `ignoreMissingXmlDocs` that is set to `false` by default in the overload that takes a single DLL and `true` in the overload that takes a list of DLLs

?

**Comment by dsyme** [comment]
Closing this old issue as by design at the moment.  We need to XML to do realistic processing
