### ISSUE TITLE
Strikethrough markdown syntax not supported

### ISSUE THREAD

**Issue by blumu** [fsprojects/FSharp.Formatting#350]
The following strikethrough syntax `~~FOO~~` with double tildes is not currently supported.
- The expected result is: ~~FOO~~
- The actual result is: ~~FOO~~

**Comment by tpetricek** [comment]
Is this a standard Markdown syntax? I had a quick look at CommonMark and that does not seem to do this: http://spec.commonmark.org/dingus/?text=foo%20~~bar~~%20ggg

That said, we could still add this feature, it looks pretty sensible :)

**Comment by blumu** [comment]
It's supported in github markdown syntax. Not sure about CommonMark.

-----Original Message-----

**Comment by matthid** [comment]
`<s>test</s>` does work and is compatible with CommonMark. However I think a PR would be accepted if someone wants it badly :)

**Comment by dsyme** [comment]
Closing as there is a workaround and no PR was made
