### ISSUE TITLE
Allow definition of properties in markdown for use during Razor processing

### ISSUE THREAD

**Issue by blumu** [fsprojects/FSharp.Formatting#353]
Right now it does not seem possible to define properties (like `@Foo`) within a markdown page and refer to it from a razor template. Such feature would for instance allow blog scenarios where metadata like blog post dates and author name are defined in the markdown itself and typeset in the razor template. 
Current workaround is to add a javascript snippet in the markdown defining global variables with values to be passed to the razor template and then render the content dynamically after the page is fully loaded using a windows.onLoad handler but this is ugly and introduces a delay in the rendering.

**Comment by matthid** [comment]
I solved a similar problem and posted the code here: https://yaaf.de/blog/post/2015-12-17/News%20replaced%20with%20blog

If this doesn't solve your problem feel free to suggest a syntax and an implementation.

**Comment by blumu** [comment]
For his personal website Tomas Petricek created a library called FsBlobLib which, among other things, implements this feature:
<https://github.com/tpetricek/TomaspNet.Website/blob/master/tools/FsBlogLib/BlogPosts.fs#L49>
Of course one can reuse and customize this code (which I did) but this feels like a feature that should be part of FSharp.Formatting. Also the implementation in FsBlogLib generates intermediate files that are subsequently processed by FSharp.Formatting. Ideally the stripping of the blog header should be performed in-place in memory and the blog content directly pipped to the formatter.

**Comment by matthid** [comment]
I would agree on an API that allows to do it on the caller side (would https://github.com/tpetricek/FSharp.Formatting/issues/359 help?), but I don't think we should add a blog post only feature to the library.

**Comment by matthid** [comment]
That said, maybe a FSharp.Formatting.BlogPost Library providing those extensions would make sense?

**Comment by dsyme** [comment]
Razor templating has been removed, and the templating we do have allows property substitution
