### ISSUE TITLE
processDirectory should pass the relative path to the site root on each call to the Razor template

### ISSUE THREAD

**Issue by blumu** [fsprojects/FSharp.Formatting#354]
When using processDirectory with a given razor template, the razor template may refer to various static resources (like css and images). Because files generated by processDirectory may reside in different subdirectories the template cannot rely on relative paths to refer to static resources. Instead one has to use absolute URLs generated using the @Root variable. The problem is that this prevents you from using the same set of HTML files for local view or when publishing to an online website.
It would be nice instead if processDirectory could generate a property containing the relative path from the output directory of the processed file to the root of the site.

**Comment by drvink** [comment]
I wasted hours on this, unable to figure out why all HTML output from `FSharp.Formatting` looked broken--I even tried generating docs for different projects on different machines--until I found this issue. Please prioritize fixing this, or at least make a prominent note somewhere that the issue exists so that other people don't get caught by it.

**Comment by tpetricek** [comment]
I marked this as planned - it is a breaking change, but I think nobody can possibly rely on the current (non-sensical) behavior. 

@drvink If you can help us fix this, that would be great! It should be just a matter of changing the `processDirectory` function [here](https://github.com/tpetricek/FSharp.Formatting/blob/f4a3119dc8060704402622bf701a2618cdfc5bf5/src/FSharp.Literate/Main.fs#L199).

**Comment by dsyme** [comment]
Razor templating has been removed
