### ISSUE TITLE
Literate.ProcessMarkdown should write to Stream instead of disk file 

### ISSUE THREAD

**Issue by blumu** [fsprojects/FSharp.Formatting#359]
HTML generators like `Literate.ProcessMarkdown` and `Literate.ProcessDocument` should ideally write the output to a .Net `Stream` rather than a file on disk. This would allow in-memory processing and efficient composition of different stream processors.

**Comment by cdrnet** [comment]
(or to a TextWriter)

**Comment by matthid** [comment]
I totally agree and would accept an PR (Thought about this but never actually had time to do it). I don't think it is very invasive, however we should try to keep the current API (but I don't mind breaking changes and doing a v3 release).

**Comment by dsyme** [comment]
I have gone over the current API and think we shouldn't do this.  Just write a temp file is enough, we have to keep the API simple.

**Comment by dsyme** [comment]
I have gone over the current API and think we shouldn't do this.  Just write a temp file is enough, we have to keep the API simple.
