### ISSUE TITLE
[Question] Explicit including APIs in the docs

### ISSUE THREAD

**Issue by dnauck** [fsprojects/FSharp.Formatting#363]
Currently it is possible to [exclude APIs from the docs](http://tpetricek.github.io/FSharp.Formatting/metadata.html#Excluding-APIs-from-the-docs).

Is it also possible to generate API docs just for types and marked fields, properties, etc. that are explicit marked?

I only want to document some special types and some public fields of them from an larger assembly.

**Comment by matthid** [comment]
AFAIK we currently can only filter non-public stuff and manually via `omit`

**Comment by dnauck** [comment]
Any news on this?

**Comment by tpetricek** [comment]
We still don't have this, but I'd be happy to accept a PR that adds this feature.

**Comment by dsyme** [comment]
Closing this old feature request

**Comment by dnauck** [comment]
Oh, this is still a valid request ;)

**Comment by dsyme** [comment]
Hi @dnauck would you like guidance on how to contribute this feature? We'd accept it if you want to contribute it and would use it. It's not hard to implement tbh. 

Otherwise this is not on the roadmap and I'll close it (though we'd accept it in the future if someone decides to do it)

**Comment by dsyme** [comment]
Closing this old issue, `fsdocs` is very different now
