### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by ForNeVeR** [fsprojects/FSharp.Formatting#375]
At [the end of Library Documentation page](http://tpetricek.github.io/FSharp.Formatting/metadata.html#Work-in-progress) there are two broken links leading to https://github.com/BlueMountainCapital/Deedle/blob/master/tools/build.fsx and https://github.com/BlueMountainCapital/Deedle/tree/master/tools/reference.

**Comment by wallymathieu** [comment]
This seems to be an old issue from before the library was moved to fsprojects. I'm closing it for now.
