### ISSUE TITLE
It would be nice if reference documentation for types included implemented interfaces

### ISSUE THREAD

**Issue by ReedCopsey** [fsprojects/FSharp.Formatting#378]
When `MetadataFormat.Generate` runs, the reference doesn't include implemented interfaces. 

This is especially problematic if you have interfaces defined by other interfaces, which is occasionally useful.  The resulting documentation, such as [this example](http://reedcopsey.github.io/Gjallarhorn/reference/gjallarhorn-idisposableview-1.html) , is far less useful than if it were to list out the interfaces that are implemented/inherited.

**Comment by ReedCopsey** [comment]
Perhaps a better example would be [here](http://reedcopsey.github.io/Gjallarhorn/reference/gjallarhorn-bindable-inotifycommand.html).

It'd be nice, in this case, to have the API documentation reflect [this line of code](https://github.com/ReedCopsey/Gjallarhorn/blob/master/src/Gjallarhorn.Bindable/Contracts.fs#L14), as it's critical to understanding the purpose of the interface.

**Comment by matthid** [comment]
I agree, this would be a nice addition. A PR for this would be appreciated. To get startet one would add a field to [TypeInfo](https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/Main.fs#L146) and then use it in the [template](https://github.com/tpetricek/FSharp.Formatting/blob/master/misc/templates/reference/type.cshtml#L31) like Namespace.

**Comment by ReedCopsey** [comment]
Just a note in case anybody tackles this - The field would need to allow for multiple interfaces to be listed, as well (not a single like the parent module).

**Comment by dsyme** [comment]
Covered by #424
