### ISSUE TITLE
Problem when rendering type hints in API docs

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Formatting#39]
Hi,

I have some type hints in FAKE:

![image](https://f.cloud.github.com/assets/57396/1343634/30817736-3676-11e3-8f9a-35e40046618c.png)

it is rendered as:

![image](https://f.cloud.github.com/assets/57396/1343611/f045594e-3675-11e3-9487-04a69e5e7742.png)

Cheers,
Steffen

**Comment by dsyme** [comment]
I think we should close out really old issues like this one
