### ISSUE TITLE
Allow markdown as output kind

### ISSUE THREAD

**Issue by FoggyFinder** [fsprojects/FSharp.Formatting#393]
I wanted to make some changes to .md file, and then save it back in .md the format.

But I have not found such a function in a static Markdown class:

http://tpetricek.github.io/FSharp.Formatting/reference/fsharp-markdown-markdown.html

There are functions only for HTML or LaTeX format.

**Comment by tpetricek** [comment]
This is not supported yet, but it would be a great addition!

In fact, I needed this already - I wrote just a sketch that handles a couple of node kinds. Feel free to take it and extend it :-) https://github.com/the-gamma/TheGamma/blob/master/web/code/document.fs#L36

**Comment by dsyme** [comment]
> I wanted to make some changes to .md file, and then save it back in .md the format.

Just to mention the latest release has added the ability to ouput `.fsx`.  Adding `.md` output shouldn't be too hard

**Comment by dsyme** [comment]
Feature implemented by @queil
