### ISSUE TITLE
FSI parameter output in F# formatting page

### ISSUE THREAD

**Issue by mvkara** [fsprojects/FSharp.Formatting#398]
Not sure where to get help on this issue. When generating documentation using the standard ProjectScaffold template I'm getting the FSI output at the end of my HTML pages. Obviously the more inline code I have in my page the more variables are printed at the end of my HTML.

An example is below of what gets appended to the resulting HTML webpage generated by F# Formatting. Hopefully this is the place to get help on an issue I'm not sure how to fix.

namespace System
namespace System.IO
Multiple items
type LiteralAttribute =
  inherit Attribute
  new : unit -> LiteralAttribute

Full name: Microsoft.FSharp.Core.LiteralAttribute

---

new : unit -> LiteralAttribute
val scriptDir : string

Full name: Tutorial.scriptDir
val generate : unit -> 'a

Full name: Tutorial.generate
val typeof<'T> : System.Type

Full name: Microsoft.FSharp.Core.Operators.typeof
type InlineSimpleScript = obj

Full name: Tutorial.InlineSimpleScript
type ParentType = obj

Full name: Tutorial.ParentType

**Comment by tpetricek** [comment]
This looks like the output you'd see if the CSS is not loaded properly - those are the tool tips that should only appear when you move mouse over some identifiers in source code, but should be hidden by CSS.
