### ISSUE TITLE
lineNumbers can't be turned off with the command line tool

### ISSUE THREAD

**Issue by AnthonyLloyd** [fsprojects/FSharp.Formatting#402]
Target "Posts" (fun _ ->
    FSharpFormatting.run "literate --processDirectory --inputDirectory  posts --outputDirectory _posts --lineNumbers false" 
)

Sorry I've not been able to investigate further but thought I would report

**Comment by tpetricek** [comment]
A PR that makes this possible would be great.

**Comment by AnthonyLloyd** [comment]
Looks like a problem is with CommandLineParser gsscoder/commandline#115.
They said they won't fix until 2.0 but I'm not sure it is really being maintained.

**Comment by dsyme** [comment]
This was completed, thanks
