### ISSUE TITLE
Markdown metadata

### ISSUE THREAD

**Issue by onionhammer** [fsprojects/FSharp.Formatting#409]
It would be great to have support for metadata (like many other markdown implementations - multimarkdown, etc)

https://pythonhosted.org/Markdown/extensions/meta_data.html

Essentially you can put metadata at the top

```
Title:   My Document
Summary: A brief description of my document.
Authors: Waylan Limberg
         John Doe
Date:    October 2, 2007
blank-value: 
base_url: http://example.com

first paragraph
```

**Comment by tpetricek** [comment]
I wouldn't be strictly against adding something like this, but it is something that can already be easily done. For example, the Fable documentation (see for example [this page](https://raw.githubusercontent.com/fsprojects/Fable/master/docs/source/docs/compatibility.md)) uses ordinary Markdown lists, e.g.:

     - tagline: Supported F# language features and libraries

    # Heading
    rest of the page...

Which are then extracted in a pre-processing step: https://github.com/fsprojects/Fable/blob/master/docs/docs.fsx#L131

So I think there is not really need for a separate syntax for this.

**Comment by dsyme** [comment]
Closing this old issue (reopen if you think it's really important)
