### ISSUE TITLE
Request: remember source spans

### ISSUE THREAD

**Issue by ljw1004** [fsprojects/FSharp.Formatting#410]
I'd love if the `MarkdownParagraph` and `MarkdownSpan` types contained information about which span in the original .md source file they refer to.

(Scenario: I use FSharp.Formatting to parse markdown, then I process it, and if there was anything wrong then I'd like to report which line number it was wrong at.)

**Comment by ljw1004** [comment]
By the way, I'm currently using a HIDEOUS workaround...
https://github.com/ljw1004/mdspec2docx/blob/master/mdspec2docx/fuzzy-string.cs

Basically, I render an FSharp.MarkdownParagraph into a series of words (a rough alphanumeric-only representation of what the original markdown might have looked like). And I convert the original markdown source code into a series of words with known text spans. And I use a fuzzy word-matching algorithm to figure out where the MarkdownParagraph likely matches up.

:(

**Comment by AviAvni** [comment]
@ljw1004 please look https://github.com/tpetricek/FSharp.Formatting/pull/411
