### ISSUE TITLE
No github links for csharp

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FSharp.Formatting#413]
Genarating docs for a solution with both F# and C#, the github links for F# are generated correctly, but there are no github links for the C# project. Is this by design, or should they be there?

**Comment by tpetricek** [comment]
I think this is not supported. Happy to accept PR that adds this :)

**Comment by matthid** [comment]
I think this needs to be added to FCS and is not trivial :)

**Comment by dsyme** [comment]
@matthid I think we should close out all issues involving using FSharp.Formatting for formatting C# assemblies.  What works works, what doesn't seems out of scope.  What do you think?

**Comment by matthid** [comment]
I think good C# support could have been a good way to attract C# developers at the time. I'd say that time has passed and they use different tools nowadays. While it might still be a good idea to support C#, there is probably no benefit in keeping the issues open.

**Comment by dsyme** [comment]
@matthid Yes agreed

**Comment by forki** [comment]
AFAIK we still have users in mixed language projects.

Don Syme <notifications@github.com> schrieb am Sa., 13. Apr. 2019, 01:54:

**Comment by dsyme** [comment]
I am closing this as it isn't a goal to be a perfect c# doc generator. Someone can contribute it I guess but it's not a bug or even a feature on the roadmap
