### ISSUE TITLE
Expand processing into .fs files

### ISSUE THREAD

**Issue by WovenTales** [fsprojects/FSharp.Formatting#420]
I'm writing a library using the literate comment style, and while I've gotten the command line tool to work with that using the `metadataFormat` flag, the generated documentation is, as expected, not taking advantage of the paragraphs of prose. I've not had as much luck getting the `literate` flag to run (I want to work with it a bit more to make sure it's not my error before submitting another issue), but the times it has, the tool successfully generated a sparse file for the `Script.fsx` that Visual Studio created (and I've since removed) and completely ignored the `Parser.fs` containing my code and all of the documentation.

I'm not creating an executable script -- I do want it to just be a .dll -- but part of the reason I've done this is to force myself to document my code well, and it would be a shame to never see what the Markdown results in. Is there something in the interactive environment you're leveraging to render the documentation, that makes reading the static files more difficult?

**Comment by tpetricek** [comment]
When you compile `fs` files, the compiler puts triple `///` XML comments before members into a `xml` file that's generated as part of compilation, but all other comments are erased.

We could process other kinds of comments in `fs` files from the source code before compilation, though this would require modifying the literate parser so that it handles ordinary source files and not just scripts.

**Comment by WovenTales** [comment]
Ah, that makes sense. I'd still definitely like to have that ability in the future, but I can see why it hasn't been implemented yet. Thanks!

**Comment by tpetricek** [comment]
If you're interested in proposing how this could work & putting together a PR, we would be happy to help & accept it - and I'm sure there would be interest in wider community too. I think we'd need more concrete idea how this should work (I have only vague understanding so far.)

**Comment by dsyme** [comment]
Closing this old issue (spring cleaning)
