### ISSUE TITLE
incorrect parsing

### ISSUE THREAD

**Issue by tomcl** [fsprojects/FSharp.Formatting#426]
```
type DUList = | StringListNode of (string * DUList) | Empty
```

Results in a parse with the string type noted as "multiple items" `value 'T -> string` or `System.string`. this breaks parsing of the D.U. Replacing string by int for example does not change this. It seems that in this fragment the parser does not realise that the thing after the `of` must be a type. Whereas of course this works fine with real parsing.

also, this breaks subsequent parsing unless I put it into a separate module e.g. `[module=NoParse]`

I can investigate further, with a clean uptodate version of Fsharp.Formatting, if this is not some weird error of mine?

**Comment by dsyme** [comment]
Closing this old issue
