### ISSUE TITLE
Table in HTML/Latex

### ISSUE THREAD

**Issue by emmanuelchevallier** [fsprojects/FSharp.Formatting#427]
Hi,

Wy try to move our reports to Fsharp from R.
Fsharp.Formatting will be able to manage HTML/LaTex table ?

Actually we use the [xtable R packages](https://cran.r-project.org/web/packages/xtable/vignettes/xtableGallery.pdf) to do that in LaTex.

Do you recommend to use R package like xtable, kable or stargazer via Rprovider ?

Thanks,
Best regards,
Emmanuel

**Comment by dsyme** [comment]
Closing this old question
