### ISSUE TITLE
Some lInks of FSharp.Formatting in the README.MD are broken

### ISSUE THREAD

**Issue by eriawan** [fsprojects/FSharp.Formatting#436]
Some links on README.MD about FSharp.Formatting are broken, especially links under Documentation section: https://github.com/tpetricek/FSharp.Formatting#documentation:

![image](https://cloud.githubusercontent.com/assets/8773147/25595981/24d25f8c-2ef1-11e7-949a-93c940637e83.png)

Those two links are pointing to non-existing web page (404) anymore. Are the links changed to other URL?

cc @matthid , @tpetricek

**Comment by matthid** [comment]
Yes we try to move to fsprojects :)

**Comment by eriawan** [comment]
@matthid thanks! Let me know if you are done moving to FsProjects. 👍

**Comment by matthid** [comment]
I think we are :)
