### ISSUE TITLE
Tooltips not being generated in VS2017/FSI v4.1

### ISSUE THREAD

**Issue by aaron-comyn** [fsprojects/FSharp.Formatting#442]
It appears that tooltips are not being generated when VS2017 & FSI 4.1 is used to generate documentation.  The generated website contains a `<div class="span1"></div>` instead of the normal set of `<div class="tip" id="fs1"...` tags.

I have not tested this with FAKE or any other task runner.

Steps to reproduce:

Run processScriptAsHtml () in FSharp.Formatting\literate\build.fsx on in VS 2017 (F# Interactive version 4.1).  Run the same function from the same script in VS 2015 (F# Interactive version 14.0.23413.0).  
The resulting FSharp.Formatting\literate\output\demo-script.html will differ.

Happy workaround:

Run the same function from the same script in VS 2015 :)

----

Minor side note:

build.fsx calls `#load "../../src/FSharp.Formatting.fsx"` from projectscaffold, instead of the relative path to the packages script (`../FSharp.Formatting.fsx`) .  [I woulda sent a PR if it weren't for the impact across projects...]

**LOVE** this library!

**Comment by kurtschelfthout** [comment]
Confirmed. Same with a run from FAKE or a manual run from FSI 4.1. Somehow using FSI 4.1 breaks FSharp.Formatting.

**Comment by kurtschelfthout** [comment]
Very likely just needs a package update as in #441. The FSharp.Compiler.Service used is locked to 2.0.0.8 which is ancient.

**Comment by wallymathieu** [comment]
Is this still the case when using the beta of the library?

**Comment by kurtschelfthout** [comment]
@wallymathieu  Probably. This project is essentially dead. Last release (the beta) was in 2016 according to NuGet.

**Comment by matthid** [comment]
> This project is essentially dead. Last release (the beta) was in 2016 according to NuGet.

@kurtschelfthout Not that I'm aware of. Latest releases are on AppVeyor, use `source https://ci.appveyor.com/nuget/fsharp-formatting` in your `paket.dependencies`

**Comment by kurtschelfthout** [comment]
I finally updated to the latest release on the appveyor feed and can confirm that fixes the issue.

**Comment by wallymathieu** [comment]
I'm closing the issue @kurtschelfthout 😄
