### ISSUE TITLE
NuGet package does not match TargetVersion in assemblies

### ISSUE THREAD

**Issue by conniey** [fsprojects/FSharp.Formatting#447]
The assemblies inside [FSharp.Formatting/3.0.0-beta01](https://www.nuget.org/packages/FSharp.Formatting/3.0.0-beta01) live under: lib\net40 but the assemblies inside are actually compiled against .NET 4.5.  The assemblies in master branch are compiled against .NET 4.6.1.

**Repro Steps:**
1. Download [FSharp.Formatting/3.0.0-beta01](https://www.nuget.org/packages/FSharp.Formatting/3.0.0-beta01) 
2. Unzip package
3. `ildasm .\fsharp.formatting.3.0.0-beta01\lib\net40\FSharp.Formatting.Common.dll`
4. Examine the manifest and look for `TargetFrameworkAttribute`

I can help fix this issue. I encountered this issue when trying to fix https://github.com/Antaris/RazorEngine/pull/480#issuecomment-316985979.  
The reason the that RazorEngine build step is broken is because FSharp.Formatting references System.Web.Razor but the PR uses Microsoft.AspNetCore.Razor.  I want to migrate this project to use RazorEngine.Razor. What do you think @matthid ?

**Comment by matthid** [comment]
Yes this is due to historical reasons. I guess now that we have an include script there is an option to change this for v3...

I'm fine with the upgrade. What makes me sleepless are the new dependencies of the AspNetCore package and how we can handle them in a sane way in the load script...

**Comment by matthid** [comment]
Maybe we need to no longer bundle and load the paket generated load script...

**Comment by conniey** [comment]
@matthid I understand your fears. The good thing about those new dependencies is that if you crack them open and peer into the lib\net45 folder, it contains a placeholder _._.  This means that there are no extra assemblies needed to run this package and can be found in the GAC. From: https://github.com/aspnet/Home/issues/744#issuecomment-123411563

![image](https://user-images.githubusercontent.com/10136526/29202283-9126ad54-7e1b-11e7-94f9-3d2a58f13ba7.png)

https://github.com/conniey/FSharp.Formatting/tree/replaceWithRoslyn Is a branch where I replaced RazorEngine with RazorEngine.Roslyn and the `build.cmd` works end to end... Although, there may be other things that are required to verify that it works.

**Comment by conniey** [comment]
@matthid Any feedback? Does this approach work? Can I open a PR with the branch where it replaces RazorEngine with RazorEngine.Roslyn?

**Comment by matthid** [comment]
Question is: Are there also no reference assemblies required to compile? Problem with FSharp.Formatting is that we basically "compile" at runtime, which means it is not enough for us that the assemblies are not required at runtime.
I really want to look at FSharp.Formatting again and find a solution for netcore, but currently we are heavily focused around bringing Paket and FAKE up and running again :)

Moving to `RazorEngine.Roslyn` is definitely a good first step to verify that everything will still work. I should have provided a beta release of your netcore work in RazorEngine a long time ago. Hopefully I can get back to this soon. If you want you can ping me on skype (matthi dot d at live de) if I again do not respond in a reasonable time span (<week) sorry :)

Your changes look good to me yes PR is a good idea. Question is will we change that back once we replace CodeDom with Roslyn in the normal "RazorEngine" package?

**Comment by conniey** [comment]
> Question is: Are there also no reference assemblies required to compile? Problem with FSharp.Formatting is that we basically "compile" at runtime, which means it is not enough for us that the assemblies are not required at runtime.

Can you send me a project that uses FSharp.Formatting that I can test this behaviour on? I don't think there should be any other reference assemblies (because Microsoft.AspNetCore.Razor's dependencies' package folders are empty) used to compile other than RazorEngine.Roslyn.  But I'll double-check.

> Your changes look good to me yes PR is a good idea. Question is will we change that back once we replace CodeDom with Roslyn in the normal "RazorEngine" package?

Yes, we would change it back to the normal RazorEngine package.  The initial reason for this proposed PR change was because https://github.com/Antaris/RazorEngine/pull/480#issuecomment-319210847 would break that existing test to make sure FSharp.Formatting works. But after https://github.com/Antaris/RazorEngine/pull/480 got merged and a beta released, we would revert back to using the original RazorEngine package.
To avoid this, we could also: 
1. merge in https://github.com/Antaris/RazorEngine/pull/480
2. Release nuget package
3. update FSharp.Formatting to use newest package
4. update RazorEngine tests to check for compatibility against newest FSharp.Formatting release

I am open to any options. :)

**Comment by matthid** [comment]
@conniey Any https://github.com/fsprojects/ProjectScaffold based project is using it. 
> I had reports that it is broken at the moment, this is because I'm falling a bit behind on this Library regarding dotnetcore and the V3 version.

Let me know if it works for you.

Regarding on the way forward. It probably is easier for me to accept and release the `FSharp.Formatting` change first and see that the integration test is still running. Also it should be easier for you as AFAIK this repository is already properly releasing a package in the appveyor feed (just increase the alpha version in RELEASE_NOTES). You can use this feed in RazorEngine to check if everything still works (it is just adding `source https://ci.appveyor.com/nuget/fsharp-formatting`, adding `prerelease` to the `nuget FSharp.Formatting` file and doing paket update).

In any case I'll try to get a prerelease package for RazorEngine out probably weekend. So you can go either way from there.

**Comment by dsyme** [comment]
Closing this old issue (spring cleaning)
