### ISSUE TITLE
Source Linking does not link to other repositories like TFS correctly

### ISSUE THREAD

**Issue by james-novino** [fsprojects/FSharp.Formatting#448]
When providing a sourceRepo to the MetadataFormat: 
```
MetadataFormat.Generate
    ( binaries, output @@ "reference", layoutRootsAll.["en"],
      parameters = ("root", root)::info,
      sourceRepo = tfsLink, //setting up source link to go to tfs instead of git hub
      sourceFolder = __SOURCE_DIRECTORY__ @@ ".." @@ "..",
      publicOnly = true,libDirs = libDirs )
```

When building the file links it does not properly handle URL parameters. 
For instance a correct URL would be:
 _`https://**link**/_git/repo/?path=**filepath**&line=**LineNumber**`, however even when specifying the `/?path=`_ 
The formatted Url when providing the tfsLink as _`https://**link**/_git/repo/?path`_ is: 
_`https://**link**/_git/repo//**filepath**?path=#L66-66`_
Where the bolded terms are things I would like control over. The **filepath** is something that is known from from the DLL's as is the **LineNumber**, but the rest of the formatting is predefined and only works for Git, Path.Combine does not properly handle url parameters.

**Comment by dsyme** [comment]
I'm closing this as won't fix. Or I'd reckon tfs has probably already  changed to support hut style linking
