### ISSUE TITLE
publish the 3.0.0-beta08 nupkg to Nuget.org

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Formatting#453]
Only the beta01 is available for download. 

Among other problems the nuspec points to an old version of FCS (2.0.0.6) and it contains an older version of FSharp.Formatting.fsx.

**Comment by matthid** [comment]
We publish prereleases to the appveyor feed (`https://ci.appveyor.com/nuget/fsharp-formatting`). Just add that for now.
Publishing to appveyor is easier for me.

**Comment by jackfoxy** [comment]
3.0.0-beta08 is already very good and fixes https://github.com/fsprojects/FSharp.Formatting/issues/364 (for me). Just by incorporating the latest FCS it probably fixes some other issues, too. 

My github.io pages finally have tooltips over the F# samples again.

This is ready for wider beta testing. It would be useful to publish some guidance on the changes people must make to their generate.fsx files, so they don't have to dig up the generate.fsx file in this repo.

Putting it on Nuget will encourage more beta testers.

**Comment by wallymathieu** [comment]
I've done a pull request to fix issue with rendering in F#+ https://github.com/gusty/FSharpPlus/pull/79 , it looks kind of weird to reference an outside feed.

Having a migration doc would also be nice.

**Comment by jackfoxy** [comment]
+1 to migration doc. I had to piece it together myself. I won't have time myself to put together such a doc in the near future. Maybe in a couple of weeks.

**Comment by wallymathieu** [comment]
But I'm not sure that helps

**Comment by jackfoxy** [comment]
For myself, and probably for most people, it is the changes necessary for to the generate.fsx file that many people have from Project Scaffold.

**Comment by wallymathieu** [comment]
Where did you integrate the beta?

**Comment by wallymathieu** [comment]
So that we can perhaps compile a list of changes needed?

**Comment by jackfoxy** [comment]
Both of these projects source FSharp.Formatting 3.0.0-beta08 with Paket from https://ci.appveyor.com/nuget/fsharp-formatting

https://github.com/jackfoxy/DependentTypes

https://github.com/jackfoxy/FsRegex

in both git histories you will find F#.Formatting beta 8 commits. The primary change is to docsrc/tools/generate.fsx
