### ISSUE TITLE
Maintainers++

### ISSUE THREAD

**Issue by wallymathieu** [fsprojects/FSharp.Formatting#456]
Hi! 
I appreciate this fine library! We have had some minor issues with it. I can help out a bit. We @gusty @ShalokShalom noticed some problem with rendering tables. 

It was mentioned that this project looks unmaintained, why I'm willing to help out a little bit reviewing and merging pull requests in order to get a bit more flow in this project. Ping @forki

**Comment by wallymathieu** [comment]
Or should the title be ` Maintainers <- someone :: Maintainers` ? 😉

**Comment by matthid** [comment]
I don't know if we have any process around that. Typically, we hope some people start to contribute/comment/review regularly and once we are confident we give them access. But it looks like you already have the required access here on GitHub, so I'm unsure what you are asking for :).

Basically feel free to start/review PRs, manage/create/close issues and if there is anything feel free to ping me. About creating releases: I think we will find a solution once this thing indeed gets rolling again ;)

**Comment by wallymathieu** [comment]
I'm part of fsprojects, but I don't have review access to this project. So I guess I'm asking for that to begin with (if you guys are unsure about giving me merge access).

**Comment by forki** [comment]
added you as collaborator

**Comment by wallymathieu** [comment]
Thanks!

**Comment by wallymathieu** [comment]
It does seem however that I can still not review or close issues? What kind of permissions did you assign the account?

**Comment by forki** [comment]
Collaborator with read. I will assign more rights when @matthid says so

Am 15.01.2018 08:44 schrieb "Oskar Gewalli" <notifications@github.com>:

**Comment by tpetricek** [comment]
@wallymathieu Thanks so much for volunteering to help maintaining this library! I'll leave the final decision to @matthid who has been the main active maintainer recently, but I would be more than happy to add you as another maintainer.

**Comment by matthid** [comment]
@wallymathieu You can ping me on skype (matthi<dot>d<at>live<dot>de) or slack if you have any particular ideas for this library or stuff you want to do. I'm not sure why everything depends on me, but my only problem is that I don't know you or what you want to do here. As you are already member I guess you have already done some things somewhere else in the ecosystem? In principle I don't have any objections.
