### ISSUE TITLE
Paket release process broke because of MissingMethod exn

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Formatting#461]
![image](https://user-images.githubusercontent.com/57396/36201331-f2a63c5a-117f-11e8-8abe-0a015b8a783c.png)

what else should I provide?

**Comment by wallymathieu** [comment]
Could it be due to FSharp.Formatting being built with an old fsharp compiler?

**Comment by matthid** [comment]
Yes I think updating everything to latest and updating the FSF package in Paket would solve this.

**Comment by wallymathieu** [comment]
Would making it a tool help keep it separate from the other dependencies?

**Comment by dsyme** [comment]
> The problem is that FCS doesn't try to keep anything stable. They use semver now but all they do is increase the Major version number on every release :/

This is a good point to insert an apology for this.

Unfortunately we really have to do it, because too much of the F# compiler internals got exposed in early FCS versions, especially the untyped syntax trees.

Still, we don't release FCS that often...
