### ISSUE TITLE
Perf regressed in 3.0?

### ISSUE THREAD

**Issue by ovatsus** [fsprojects/FSharp.Formatting#465]
I don't have any numbers, so this can just be my wrong perception, but it seems that the time it takes to generate the docs for FSharp.Data after updating to 3.0 is noticeable longer. I have no clue what's included in 3.0, so not sure if that's expected or not. MetadataFormat.Generate seems about the same, it's the Literate.ProcessDirectory that seems to be longer

**Comment by wallymathieu** [comment]
Version of FSharp.Formatting: https://github.com/fsharp/FSharp.Data/blob/master/paket.lock#L351-L355

**Comment by matthid** [comment]
Numbers and perf tests would help ;)

**Comment by ovatsus** [comment]
FSharp.Formatting 2.14.4 on FSharp.Data 2.4.6 instead of FSharp.Data master (which is probably a fairer comparison since FSharp.Formatting 2.14.4 on FSharp.Data master wasn't generating the docs properly):

Reference Documentation took 00:00:11.0434135 to generate
Library Documentation took 00:01:52.5381516 to generate

So reference docs went from 11 seconds to 17 seconds (not a big deal), but the library docs went from 2 minutes to 4 minutes

**Comment by matthid** [comment]
Do you have some tracing tool to track that down further? (Because I'm not able to look at this anytime soon).
Also we might remove razor by default and switch to something like fulma... So this is not high priority for me ;)

**Comment by ovatsus** [comment]
Please don't remove Razor support. FSharp.Formatting 2 only supports that, and if you remove it it will jsut cause most people to never upgrade to version 3

**Comment by wallymathieu** [comment]
The intention is not to remove it, but be able to use other things rather than razor.

**Comment by matthid** [comment]
Yes sorry, wrong words. It will no longer be the default but still supported

**Comment by matthid** [comment]
And that still needs a working implementation first, so...

**Comment by dsyme** [comment]
Clearing out old issues that won't realistically be investigated
