### ISSUE TITLE
Microsoft.Build.Utilities.Core?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.Formatting#466]
I've used FSharp.Formatting template to generate reference documentation by ProjectScaffold.

Suddenly it has been starting to fail a month ago (about 14/03/2018) by the issue:

```
error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 
The system cannot find the file specified.
```

...and meanwhile I do have multiple copies of the file in my nuget package folders, I don't know what is searching for it and where should it be. It can be also that some Visual Studio update broke this, I don't know. Updating FSharp formatting to 3 beta didn't help.

**Comment by Thorium** [comment]
Not sure, but this could be related to fsi binding redirects as the file is version 14 and there is version 15 available...

**Comment by wallymathieu** [comment]
You can try upgrading to v3: [upgrade_from_v2_to_v3.md](https://github.com/fsprojects/FSharp.Formatting/blob/master/docs/content/upgrade_from_v2_to_v3.md)
