### ISSUE TITLE
Using FSIEvaluators with the console tool

### ISSUE THREAD

**Issue by kMutagene** [fsprojects/FSharp.Formatting#476]
We are using the console tool with [Project Scaffold](https://github.com/fsprojects/ProjectScaffold) to build our docs. As using the special commands shown in the [literate programming example](http://fsprojects.github.io/FSharp.Formatting/literate.html) throw the following error:
<pre>Error on RazorLiterate.ProcessDirectory:
System.Exception: Output, it-value and value references should be replaced by FSI evaluator </pre>
How should fsi evaluators be used when using the command line tool? There must be a specific thing that i am missing here, but using the example provided in [embedding output](http://fsprojects.github.io/FSharp.Formatting/evaluation.html#Specifying-the-evaluator-and-formatting) gets formatted like any other f# snippet.

**Comment by kurtschelfthout** [comment]
You need to somehow pass `—fsieval` to the console tool, or it won’t evaluate the snippets. 

Unfortunately the FAKE wrapper does not have that option, so for now I just copy-pasted the wrapper code in my build.fsx directly and added the argument.

**Comment by kMutagene** [comment]
Thank you, this is what i was looking for.
