### ISSUE TITLE
Dead links on documentation

### ISSUE THREAD

**Issue by tmonte** [fsprojects/FSharp.Formatting#477]
I'm trying to setup the FSharp.FormattingCommandTool for a project. Right now I am able to generate html files for my docs without any hints on the types (all of them are objs). I tried to find examples in the documentation but it is really difficult to follow.  On the last paragraph, for example, the FAKE commands link is dead, as well as the template file link:

https://fsprojects.github.io/FSharp.Formatting/commandline.html

**Comment by wallymathieu** [comment]
Good catch! This is indeed bugs in the documentation. Since you might have the correct links, do you have a pull request in the making?

**Comment by kurtschelfthout** [comment]
It’s really confusing right now, but essentially all FSharp.Formatting versions on NuGet are out of date, and use a very old version of the F# compiler version.  So it doesn’t type newer F# programs. 

Try updating FSharp.Formatting to the latest version from the AppVeyor feed (scaffold shows how).
