### ISSUE TITLE
Code blocks in generated documentation files cannot properly display long lines

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsprojects/FSharp.Formatting#478]
![image](https://user-images.githubusercontent.com/12659251/44627862-17f81180-a93e-11e8-9221-f4b9446a5407.png)

**Comment by wallymathieu** [comment]
In order to fix this issue, you need to determine what the correct way of displaying long lines is. Say for certain projects it might be the correct way to wrap, for others, definitely not. Being able to configure the wrapping behaviour or style it in css would probably be preferable.

**Comment by teo-tsirpanis** [comment]
@wallymathieu, even if lines must wrap, we have to properly align the line numbers like Visual Studio Code does.

---

Can we use a 3rd-party code viewer component? Having a code editor component is not the focus of the product. Besides, not reinventing the wheel would bring more advantages:

* Syntax highlighting will be performed automatically by the component itself. No more complicated `<span>`s inside code snippets.

* If the component natively supports tooltips, we can display them this way, instead of relying on the IMHO crude `tips.js`. After trying to upgrade a site of mine to a newer version of Bootstrap (don't remember if it was 3 or 4), the tooltips were not shown right above the mouse.

**Comment by wallymathieu** [comment]
I didn't notice the line numbers. I've added type bug to the issue.

**Comment by wallymathieu** [comment]
Is it this component that does the thing? @eiriktsarpalis https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.CodeFormat/HtmlFormatting.fs

There seems to be a latex formatter as well. If it's pluggable then adding 3rd party compatible output should be feasible. Though I've not looked deeper into it.

**Comment by wallymathieu** [comment]
What does vscode use to format f#?

**Comment by teo-tsirpanis** [comment]
> What does vscode use to format f#?

@wallymathieu, the term _format_ has differing meanings. If you mean _auto-indent_, [it doesn't](https://github.com/ionide/ionide-vscode-fsharp/issues/274). If you mean, whatever-this-project-does, it doesn't again, assuming I have understood your question.

**Comment by wallymathieu** [comment]
I think you have understood it. Being able to swap out different formatters could be helpful.

**Comment by teo-tsirpanis** [comment]
Fixed as of the latest version. A scrollbar is shown on code blocks with long lines.
