### ISSUE TITLE
Can’t avoid line numbers with command line tool

### ISSUE THREAD

**Issue by kurtschelfthout** [fsprojects/FSharp.Formatting#479]
The command line tool has `—lineNumbers` which defaults to `true`. Unfortunately that means you effectively can not turn it off looks like  - because CommandLineParser interprets absence of the arg as the default, and presence of the arg as true also. 

Lmk if I missed anything here. 

If not, any preference for changing the default to false, OR changing the switch to `—noLineNumbers`? Happy to PR either.

**Comment by wallymathieu** [comment]
Is this flag used today by any project? It could be a remnant from earlier times. Adding ,`-noLineNumbers` flag should be safe, so that the CLI API is backwards compatible. Though, since the current version is in beta, there could be a reason to make a breaking change.

**Comment by kurtschelfthout** [comment]
> Is this flag used today by any project?

Who knows? :) If it's used, it's basically pointless. The Fake 5 wrapper for this tool does not expose any option to remove line numbers, so at least from that side there isn't any usage.

Your call.

**Comment by wallymathieu** [comment]
Looks like @fbmnds and @Krzysztof-Cieslak are the ones who has touched the code lately (2-5 years), so could perhaps give some insights into the intent. I'm not in charge of this project. I try to help out because I like the library. I think @matthid is the one who does most of the work right now.

**Comment by wallymathieu** [comment]
I think the comment about a PR still stands. If you send in a PR that fixes the issue people would be happy to accept it.

**Comment by wallymathieu** [comment]
There seems to be some documentation that mentions some of the behavior. Since the default is to have line numbers, perhaps better to change the semantics to be able to disable them. What does @matthid think?

**Comment by kurtschelfthout** [comment]
Totally happy to PR, just want any maintainer to make a call on whether they'd prefer to switch the default of `--lineNumbers` to false (which would turn off linenumbers for everyone silently) or whether they'd prefer to remove `--lineNumbers` altogether and add a `--noLineNumbers` option instead (which keeps the current default but any current superfluous usage of `--lineNumbers` would fail. )

I would suggest to do the second, at least it doesn't silently change behavior.

**Comment by wallymathieu** [comment]
I'd prefer the second alternative to be honest (since the current cli flag does not add value).

**Comment by matthid** [comment]
Yes I agree `--noLineNumbers` is fine as most people probably want line numbers and it is better to not break stuff if possible?

**Comment by wallymathieu** [comment]
If you are paranoid about the usage, then you could have `--lineNumbers` as a dummy parameter that gives you warning. But I'm not sure if it's worth the effort.
