### ISSUE TITLE
Q: command line tool hasn't got all MetaDataFormat arguments

### ISSUE THREAD

**Issue by stijnmoreels** [fsprojects/FSharp.Formatting#484]
The command line version hasn't got the
- `markDownComments` and
- `publicOnly`

command linearguments defined to send with the `MetaDataFormat.Generate` call.

Can I add them?

**Comment by wallymathieu** [comment]
What versions of the command line tool have you tried? Have you tried the one from beta channel. See issue : https://github.com/fsprojects/FSharp.Formatting/issues/475

**Comment by stijnmoreels** [comment]
Well, it was by using it via FAKE 5.0 that I saw in the `Fake.DotNet` namespace this package being used without both those arguments. Not sure what version FAKE 5.0 uses.

**Comment by dsyme** [comment]
This will be fixed by #528
