### ISSUE TITLE
Output literate programming includes intermediate FSI output

### ISSUE THREAD

**Issue by fjoppe** [fsprojects/FSharp.Formatting#486]
(was: Script Source is always included, see next comment) 

Hi,

After upgrading Project Scaffold, and converting to Fake5, I am now using FSharp.Formatting [version 3.0.0-beta13](https://github.com/fjoppe/Legivel/blob/336cfb47e4cf29044efe4623e3e6fa3e00043bdf/paket.lock#L1683). Every fsx script, which is run through the template, includes the source code of this script, somewhere at the end of the content.

**Actual Behavior**
Even though I do not pass parameter "--includeSource", it still puts the [source in the product](https://github.com/fjoppe/Legivel/blob/336cfb47e4cf29044efe4623e3e6fa3e00043bdf/docs/index.html#L136).

**Expected Behavior**
I've checked my scripts, which did not have this behavior [before this upgrade](https://fjoppe.github.io/Legivel/). And I cannot figure out what to do, to remove this content again.

**Comment by fjoppe** [comment]
After a bit diving into this issue. The above description appears to be incorrect. I was fooled, because "namespace" was at the top.

Wat really is going on, is that the intermediate output of the FSI is included. Note that I'm using literate programming from an .fsx.

So if my script has:
```fsharp
let s = "hello"
```

then at the end of the output generation, you'll see:
```fsharp
val s : string
```
This all happens within the @RenderBody() method in the template.cshtml.

It looks like as if the FSI is not running quiet. I tried [this](https://stackoverflow.com/a/20638937/4653407) in my script, but it didn't work and just added more intermediate output. Note that I've upgraded to Fsharp.Formatting 3.1 with Paket. And this also happens when I'm running the fsformattingg.exe from the commandline.


Concrete example, the input file ends here:
https://github.com/fjoppe/Legivel/blob/4c85f2e75c9b4fcfc5160f5e27faa5bc4f5c6adf/docsrc/content/index.fsx#L95

While the output continues with the intermediate FSI output here:
https://github.com/fjoppe/Legivel/blob/4c85f2e75c9b4fcfc5160f5e27faa5bc4f5c6adf/docs/index.html#L136

I'll change the title of this issue for clearance..

**Comment by dsyme** [comment]
> then at the end of the output generation, you'll see:

I believe this is because tooltip elements are not being suppressed correctly

This is normally because tip.js is not loading, e.g. see

      <script type="text/javascript" src="/FSharp.Formatting/content/tips.js"></script>
