### ISSUE TITLE
type 'FSharp.CodeFormat.CodeFormatAgent' not found in assembly 'FSharp.CodeFormat, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by precisemath** [fsprojects/FSharp.Formatting#488]
Here is what I have in my paket.dependencies file:

group NetcoreBuild
  source https://nuget.org/api/v2
  source https://api.nuget.org/v3/index.json
  framework: netstandard2.0
 
  nuget FAKE
  nuget Fake.Core.Target
  nuget FAKE.DotNet
  nuget Fake.Tools.Git
  nuget Fake.Core.ReleaseNotes
  nuget Fake.DotNet.AssemblyInfoFile
  nuget Fake.DotNet.MSBuild
  nuget Fake.DotNet.Paket
  nuget Fake.Testing.Common
  nuget Fake.Core.UserInput
  nuget Fake.DotNet.Testing.NUnit
  nuget FSharp.Compiler.Service redirects:force, content:none
  nuget FSharp.Core
  nuget FSharp.Formatting 2.14.1
  nuget FSharpVSPowerTools.Core
  nuget Fake.IO.FileSystem
  nuget Fake.Core.Trace

Here is the error message:

Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been printed  in the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing                                at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res)                                                                            at Yaaf.FSharp.Scripting.Helper.evalScript@1325.Invoke(String arg00) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.f s:line 1325                                                                                                                                                                             at Yaaf.FSharp.Scripting.Helper.save_@1298-2.Invoke(Unit unitVar0) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs: line 1299                                                                                                                                                                               at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Sc ripting\YaafFSharpScripting.fs:line 1243                                                                                                                                                at Yaaf.FSharp.Scripting.Helper.redirectOut@1269[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err, FSharpFunc`2 f) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp. Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1276                                                                                                             at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:li ne 1298                                                                                                                                                                                 --- End of inner exception stack trace ---                                                                                                                                           at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:li ne 1306                                                                                                                                                                                 at Yaaf.FSharp.Scripting.Helper.session@1328.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput(String path) in D:\a\1\s\paket-files\matthid\Yaaf.FSharp.Scripting\src\source \Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1330                                                                                                                                 at Fake.FSIHelper.runScriptUncached(Boolean useCache, IEnumerable`1 fsiOptions, Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in D:\a\1\s\src\legacy \FakeLib\FSIHelper.fs:line 565                                                                                                                                                       unknown(1,1): error FS3216: type 'FSharp.CodeFormat.CodeFormatAgent' not found in assembly 'FSharp.CodeFormat, Version=2.14.1.0, Culture=neutral, PublicKeyToken=null'. A possible c ause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.                                                                                                                                                                                           **CACHING ERROR - please open a issue on FAKE and /cc @matthid**
--

**Comment by thinkbeforecoding** [comment]
FSharp.Formatting is not netstandard2.0 due to razor dependency.
You should use FSharp.Literate instead which has no template engine integrated, but can produce html fragement from fsx or md.

**Comment by dsyme** [comment]
Closing as this has been answered
