### ISSUE TITLE
Docs needed for FSharp.Formatting.CommandTool

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Formatting#491]
I notice `FSharp.Formatting.CommandTool` is still `net461`, which means to use it you have to use Mono and .NET Framework to generate docs using this tool.

Is this expected to be the normal tool to generate docs?  Should we make this available for use on .NET Core?

**Comment by thinkbeforecoding** [comment]
As discussed in #490 only the templating is missing. Making a first netstandard2.0 version that could do the rest correctly was a primary goal.

I don't know the current state of aspnet core razor, but it was difficult to integrate, and slow to run…
If this has changed, maybe we should use that for the command tool. If not we should switch to a simpler templating engine.

**Comment by thinkbeforecoding** [comment]
The other solution would be to have f# scripts with #r "nuget: …" to load FSharp.Literate and Fable.React and a simple scaffolder that would create this script with predefined templates in elmish html.
It could then be executed with netcore version of fsi...

**Comment by matthid** [comment]
Yes this is definitely something we want. Problem boils down to:
- Porting RazorEngine dependency to netstandard, I think there is even a PR open, but it isn't maintained atm.
- Switching away from RazorEngine
- Removing Razor support (but then people can't really upgrade, it is basically a different tool at that point)

Again we decide by the first incoming PR (though I'm sceptical about removing razor support, we probably should do that in v4 at earliest when we have established something else)

**Comment by wallymathieu** [comment]
Could you boot up a local asp.net core site to do the rendering (then kill that process) in order use the same Razor as asp.net core?

**Comment by dsyme** [comment]
Other things I've noticed are

1. FSharp.Formatting on nuget can't generate docs for `netstandard2.0`
2. FSharp.Formatting on nuget uses a very old `FSharp.Compiler.Service`

https://www.nuget.org/packages/FSharp.Formatting/

Things have been updated in `master` but no nuget published.

@matthid Could you publish latest nugets?  Even if beta.

**Comment by dsyme** [comment]
Can I ask - where's the best place to get a feel for the intended usage of the command line tool?

I see a "dogfood" usage in the build.fsx, but it's not entirely clear to me that this is the intended usage model

thanks

**Comment by dsyme** [comment]
I notice that the FSharp.ProjectScaffold project is picking up nugets from appveyor (which is really not great at all... they disappear over time....)

https://github.com/fsprojects/ProjectScaffold/blob/master/paket.dependencies#L17


Also all of the logic of `generate.fsx` has been incorporated into the typical ProjectScaffold `build.fsx` here https://github.com/fsprojects/ProjectScaffold/blob/master/build.template#L212.  This is a little daunting as a usage model but I get what is happening, the [command line tool is being called from FAKE FSFormatting module](https://github.com/fsharp/FAKE/blob/694f616c97fa242162cfd36db905d7df3156018f/src/app/Fake.DotNet.FSFormatting/FSFormatting.fs#L12)

**Comment by jackfoxy** [comment]
@dsyme ProjectScaffold is only picking up Fsharp.Formatting from Appveyor, because for a very long time that was the only place the useable beta could be retrieved from. So happy to have 3.1 on nuget. I should get PS fixed this week.

**Comment by dsyme** [comment]
> @dsyme So happy to have 3.1 on nuget. I should get PS fixed this week.

Cool, I'll be updating FsLab `fsx2html` today as well

**Comment by ManuKle** [comment]
> I notice that the FSharp.ProjectScaffold project is picking up nugets from appveyor (which is really not great at all... they disappear over time....)

Is this why im getting `The NuGet source https://ci.appveyor.com/nuget/fsharp-formatting for package FSharp.Formatting was not found in the paket.dependencies file` when trying to `paket restore`?

**Comment by jackfoxy** [comment]
@ManuKle  most likely, yes.
BTW, I have updated FSharp.ProjectScaffold to get latest F#.Formatting from nuget

**Comment by dsyme** [comment]
Closing this out as there's no direct reason to doc this, it is really only used by FAKE
