### ISSUE TITLE
Identify maintainers in readme

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Formatting#495]
I'm seeing renewed interest in this project in the community. Many of the fsprojects identify the maintainers in the project readme.md. I think that would help facilitate collaboration in this project.

**Comment by dsyme** [comment]
> I'm seeing renewed interest in this project in the community. Many of the fsprojects identify the maintainers in the project readme.md. I think that would help facilitate collaboration in this project.

It's not totally clear who the maintainers are.  My main interests is to eliminate the Mono dependency that this collection of functionality induces
