### ISSUE TITLE
Documentation for commands should list them all in one place

### ISSUE THREAD

**Issue by rmunn** [fsprojects/FSharp.Formatting#498]
The various FSharp.Formatting commands like `hide`, `define-output`, and so on are documented in different places: some in https://fsprojects.github.io/FSharp.Formatting/literate.html, some in https://fsprojects.github.io/FSharp.Formatting/evaluation.html, some in https://fsprojects.github.io/FSharp.Formatting/codeformat.html, and so on. There's nowhere that lists all the available commands and what they do. I believe that list should be available somewhere in the documentation, so that people don't miss a potentially-useful command because they didn't read the page it was mentioned on.

This is not something that API-documentation tools are able to discover; someone will have to manually make a list of the available commands.

**Comment by dsyme** [comment]
The documentation has been released for 5.0.4 and this issue has been addressed, see the full table of commands available here https://fsprojects.github.io/FSharp.Formatting/literate.html
