### ISSUE TITLE
Why only *.fsx files and not *.fs?

### ISSUE THREAD

**Issue by Chiel92** [fsprojects/FSharp.Formatting#499]
Looking at the code here

https://github.com/fsprojects/FSharp.Formatting/blob/5afe8ff0e9a02bbc602c84ba3c01ddd9cf547eb9/src/FSharp.Literate/Main.fs#L200

I wonder why normal *.fs are excluded. I'd like to use literate programming for a regular project containing compiled *.fs files, not just for a set of loose scripts. Is this supported?

**Comment by thinkbeforecoding** [comment]
@Chiel92 , I think this is the classic use case to generate a website that explain how to use the library. The command line tools has been designed for this usage. It is still possible to write a F# script that uses FSharp.Formatting function to process fs files.

**Comment by Chiel92** [comment]
How could that be done easily? Executing the following code yields a bunch of individual html files, instead of a coherent document.

```fsx
let processScriptAsHtml () =
  let file = relative "demo.fs"
  let output = relative "output/demo-script.html"
  let template = relative "templates/template-file.html"
  RazorLiterate.ProcessScriptFile(file, template, output)
```

**Comment by thinkbeforecoding** [comment]
You mean, each page has a table of content that contains only the single page ?

**Comment by Chiel92** [comment]
Yes, and for instance tooltips on symbols that are defined in other files in the project should ideally be correctly generated.

**Comment by dsyme** [comment]
> I wonder why normal *.fs are excluded. I'd like to use literate programming for a regular project containing compiled *.fs files, not just for a set of loose scripts. Is this supported?

THis is not supported, but if you would like to work on it as a feature that would be great
