### ISSUE TITLE
FSharp.Literate with .NET Core 3 built-in FSI

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FSharp.Formatting#502]
For some reason (unknown for me) I cannot execute F# Script that uses `FSharp.Literate` using FSI shipped with .NET Core 3.

```
dotnet fsi docs/generate.fsx
```

<img width="1062" alt="build_cmd_—_literate-netcore3" src="https://user-images.githubusercontent.com/1197905/66273713-0bebbc80-e87f-11e9-9c52-e0f0b47609c0.png">

I've created repro repository, that can be used to reproduce the issue
https://github.com/sergey-tihon/literate-netcore3
just close and run `./build.fs`

The repo also contain `netcore3.0` console app, that do exactly the same but run as console application on top of .NET Core and works fine.

When I run script line by line I see that I fail exactly on the first call to `FSharp.Literace` - `Literate.ParseMarkdownFile`
https://github.com/sergey-tihon/literate-netcore3/blob/master/docs/generate.fsx#L30-L32

Any ideas? Can we easily release new version that uses latest FSCS?

**Comment by baronfel** [comment]
Even if you update to FCS 32 you'll likely hit what FSAC has: the set of assemblies referenced for FSI is incomplete as reported by FCS, see this issue for details: https://github.com/dotnet/fsharp/issues/7701.  We've been working a fix on this issue and associated PR at FSAC: https://github.com/fsharp/FsAutoComplete/issues/465.

**Comment by thinkbeforecoding** [comment]
@sergey-tihon @baronfel , I managed to make it run with dotnet fsi (3.0.0) in the RegexProvider repository:
https://github.com/fsprojects/FSharp.Text.RegexProvider/pull/31

If you want to have a look 😄

**Comment by dsyme** [comment]
Closing as this is now evidently working
