### ISSUE TITLE
Seems to be a mismatch with documentation and actual code for `ProcessDirectory`

### ISSUE THREAD

**Issue by PhilT** [fsprojects/FSharp.Formatting#503]
The documentation for `ProcessDirectory` (https://fsprojects.github.io/FSharp.Formatting/literate.html#Processing-entire-directories) seems to indicate that you pass it several strings: source directory, output directory and a template file. However when running the following code:

```
let source = "../content"
let output = "../output"
let template = "template.html"

Literate.ProcessDirectory (source, template, output)
```

I get the error:

```
Script is not valid:
        C:\Users\Phil\...\source\build.fsx (17,45)-(17,51): Error FS0001: This expression was expected to have type
            'OutputKind'
        but here has type
            'string'
```

EDIT: I see this is because it's expecting `format` as the third argument. I've now realised that the call is meant to be `RazorLiterate.ProcessDirectory`.

**Comment by dsyme** [comment]
This has been fixed byt the look of things, and the docs updated by @eiriktsarpalis
