### ISSUE TITLE
API Documentation page is blank

### ISSUE THREAD

**Issue by PhilT** [fsprojects/FSharp.Formatting#504]
I find it a bit funny and sad that a documentation tool has a blank API docs page.

https://fsprojects.github.io/FSharp.Formatting/reference/index.html

**Comment by PhilT** [comment]
Oh I see this may be covered by #477

**Comment by wallymathieu** [comment]
Should we close this one then?

**Comment by PhilT** [comment]
Yep, sounds like the same thing.
