### ISSUE TITLE
Documentation for the default constructor

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Formatting#51]
Hi,

writing 
![image](https://f.cloud.github.com/assets/57396/1409639/6532265c-3d96-11e3-8953-5329d8f7d501.png)

leads to:

![image](https://f.cloud.github.com/assets/57396/1409645/75c86454-3d96-11e3-8838-4cd62aaf900a.png)

How can I document the default constructor?

**Comment by dsyme** [comment]
Closing this old issue (spring cleaning)
