### ISSUE TITLE
generate script execution in FSI is broken after 35.0.0 Update from FSharp.Compiler.Service

### ISSUE THREAD

**Issue by kMutagene** [fsprojects/FSharp.Formatting#511]
Hi there, it is great that we can move to full .net core doc generation with generate scripts again. I just noticed that 4 days ago, the [FSharp.Compiler.Service](https://www.nuget.org/packages/FSharp.Compiler.Service/) got an update that broke doc generation again. The error is the following:

`System.TypeLoadException: Could not load type 'ParsedInput' from assembly 'FSharp.Compiler.Service, Version=35.0.0.0, Culture=neutral, PublicKeyToken=null'.`

When pinning a dependency to the previous version:

`nuget FSharp.Compiler.Service 34.1.1`

it works again.

**Comment by baronfel** [comment]
Yes, this library needs to establish an upper bound on the version of FCS that it supports.  I try to adhere to SemVer when publishing FCS packages, but the FCS API is not stable and so any major version release could indicate non-backwards-compatible changes.

**Comment by eiriktsarpalis** [comment]
> this library needs to establish an upper bound on the version of FCS that it supports.

We could perhaps pin to the major version, but maybe that's overly conservative? Not all breaking changes should necessarily impact FSharp.Formatting. As best practice I pin the FSCS version in the generate script dependencies.

**Comment by baronfel** [comment]
I agree! I meant to pin at the major version. I'm using https://github.com/fsprojects/SyntacticVersioning in FCS to determine how the version number needs to increment, so I am reasonably confident that version bumps that are not major versions will be compatible in the way you describe.

**Comment by eiriktsarpalis** [comment]
Fixed in 4.0.0-rc2
