### ISSUE TITLE
Best practices for docs using .NET Core

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Formatting#520]
HI All

What are the current best practices for docs using .NET Core only?

1. I know the Waypoint template is an emerging candidate.

2. Are there any examples of repos successfully migrating existing `generate.fsx` docs using FSharp.Literate etc?

Thanks

**Comment by dsyme** [comment]
cc @eiriktsarpalis @sergey-tihon I remember seeing a link to repos using only .NET Core but I'm wondering where the best working example is

**Comment by eiriktsarpalis** [comment]
If I get the question correctly, FSharp.Formatting itself already generates its own docs using .NET Core: https://github.com/fsprojects/FSharp.Formatting/blob/2c330f7aa3ec3b7926ab165195a23145f4883fde/build.fsx#L247-L251

**Comment by dsyme** [comment]
Thanks, yes.

I've also taken to just using aan application to generate the docs, will link here when I have an example
