### ISSUE TITLE
HTML value display, image serving, F# Literate programming model 

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Formatting#534]
The FsLab tool [FSharp.Literate.Scripts/fsx2html](https://github.com/fslaborg/FsLab/tree/master/src/fsx2html) adds two things over FSharp.Formatting

* HTML output/AddHtmlPrinter

* `watch` mode includes a web server for serving image content generated by HTML output

We should just integrate both of these into the `fsdocs` tool, especially now that `fsdocs` incorporates ipynb generation (which naturally involves HTML display printing).

We could also consider incorporating the HTML display aspects of .NET Interactive as part of this to get consistent HTML display and programming model extensions.

**Comment by dsyme** [comment]
I will also jot down notes about where the F# Formatting literate documentation model differs from the .NET Interactive model

### `display` 

.NET Interactive supports this magical `display` functionality:

> Each call to `display` writes an additional display data value to the notebook. You can also update an existing displayed value by calling `Update` on the object returned by a call to `display`.


```fsharp
let fruitOutput = display("Let's get some fruit!");
let basket = [| "apple"; "orange"; "coconut"; "pear"; "peach" |]

for fruit in basket do
    System.Threading.Thread.Sleep(1000);
    let updateMessage = sprintf "I have 1 %s" fruit
    fruitOutput.Update(updateMessage)

System.Threading.Thread.Sleep(1000);

fruitOutput.Update(basket);
```

**Comment by Krzysztof-Cieslak** [comment]
`AddHtmlPrinter` model that Tomas created for FsLab and [Atom FSI](http://tomasp.net/blog/2016/fslab-ionide/) back in the days seems to be way more elegant than `display` function described above. Mostly because:

* It provides separation between rendering definition and content - I don't want the script files that I render with F#.Formatting to include some magical additional functions just for rendering
* It makes more sense for full-file-processing model of F#.Formatting - with notebooks everything is focused on a cell level, while with literate programming functionalities provided by F#.Formatting we always process full script file rather than parts of it

**Comment by dsyme** [comment]
> AddHtmlPrinter model that Tomas created for FsLab and Atom FSI back in the days seems to be way more elegant than display function described above. 
> 
> So I'd vote for just porting AddHtmlPrinter to core F# Formatting rather than trying to copy APIs from notebooks which have different UX and usage patterns.

Yes, `AddHtmlPrinter` is now supported.  I don't think either model is perfect but it's sufficient.

However it's a *very* important goal (both for me, and I think the ecosystem) that notebooks produced from these documentation tools are consumable into .NET Interactive kernels.  This applies to nuget package references as well.
Realistically .NET Interactive notebooks are by far the best chance we have of getting high-quality, maintained notebook
support for the .NET ecosystem that are kept up-to-date and are complete w.r.t. other features.

So I will be contributing to `dotnet/interactive` to try to make sure we continue to hit that goal - for example to ensure .NET Interactive kernels accept `AddPrinter` and `AddHtmlPrinter` and other elements of the F# script/notebook programming model without needing extra library references or helper scripts.

**Comment by dsyme** [comment]
This is basically done for now
