### ISSUE TITLE
Tables with column groups and row groups

### ISSUE THREAD

**Issue by nhirschey** [fsprojects/FSharp.Formatting#537]
For analytic workflows, it would be nice to be able to generate nice tables with column and row groups in html and latex format:
![image](https://user-images.githubusercontent.com/5226115/87776702-14b2eb00-c820-11ea-94c6-69afd6e5b0ba.png) 

The html format would be useful for online documentation and notebooks, and the latex output would be nice for publications. I am not aware of a Markdown flavor that supports these tables, but it is possible in HTML and latex. For example, [kableExtra](https://github.com/haozhu233/kableExtra) does this for R.

Plausible approaches:
- Handle it using a printer for hierarchical Deedle or DataFrame objects.
- A set of functions like R's kableExtra
- A dsl similar to Saturn's for [HTML views](https://saturnframework.org/explanations/view.html)

**Comment by dsyme** [comment]
This is tricky. All the table input coming in assumes markdown. I don't think we want to invent our own markdown variant for this.

I think we have to regard this one as out of scope for FSF. If there was a markdown extension that dies this then I guess we'd take a PR that implemented it. But I will close as its not on the roadmap.
