### ISSUE TITLE
Detect mutable values and show this in tool tip

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Formatting#54]
Hi,

I have a mutable value (I know..):

![image](https://f.cloud.github.com/assets/57396/1415369/d3c19016-3efa-11e3-94c2-8d4c5a17da0f.png)

but this information gets lost:

![image](https://f.cloud.github.com/assets/57396/1415370/eb3df342-3efa-11e3-9792-ada7d48590df.png)

Cheers,
Steffen

**Comment by dsyme** [comment]
There's a general need to bring the tooltip displays up to quality, that's covered by other issues
