### ISSUE TITLE
Exception section in Comment.FullText doesn't resolve system exceptions

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FSharp.Formatting#545]
Per https://github.com/fsharp/fsharp-core-api-docs/pull/22, Exceptions that can't be resolved (like System.ArgumentException in the example) get an 'UNRESOLVED' marker. This is fine in general, but I think System exceptions should be resolve-able.

**Comment by Krzysztof-Cieslak** [comment]
It's way more complex for any 3rd party dependency

**Comment by dsyme** [comment]
This is fixed for .NET exceptions
