### ISSUE TITLE
Have ApiDocsModel format types using structure not text

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Formatting#549]
Currently the ApiDocsModel generates types as text not HTML.

I believe we should generate HTML as this will allow embedded links etc?

> @Krzysztof-Cieslak As a separate note, I'd like to go through and make all the type formatting generate HTML instead of strings
> 
> However this would mean the currently internalised HtmlModel being used here (note: ripped from Fornax) would be exposed as public.
> 
> Since FSharp.Formatting is at the root of the universe I think this is ok? But it could require translation from FSHarp.Formatting HTML --> Fornax HTML model
> 
> Do you think that HtmlModel should be in a single component all of its own, with a stable 1.0 version number? I was loathe to take a dependency on Fornax.Core v0.2 - for application code I would, but FSharp.Formatting is at the root of the entire universe and so I really want to avoid any significant dependencies for it.

**Comment by dsyme** [comment]
@baronfel  says

> The propagation of html rendering engines in the ecosystem is a big pain point IMO. This, fornax, giraffe, Feliz, falco all have different but similar implementations :-/

@dsyme says

> Right
> 
> I mean I've internalised it here so far, and it's currently not used in the ApiDocsModel. The use in GenerateHtml is internal.
> 
> We could give the structuring of types in the APiDocsModel without it (as a separate data model). I suppose that would be consistent with the current architecture and get the layering right

**Comment by Krzysztof-Cieslak** [comment]
How about using Giraffe.ViewEngine? https://github.com/giraffe-fsharp/Giraffe.ViewEngine

It’s 0 dependency library that we have recently taken out of core Giraffe package to allow exactly this scenario - I was planning to remove HTML DSL from Fornax Core and port Waypoint doc template to Giraffe.ViewEngine anyway

**Comment by dsyme** [comment]
> How about using Giraffe.ViewEngine? https://github.com/giraffe-fsharp/Giraffe.ViewEngine

It's possible.  

TBH for FSharp.Formatting I really want zero dependencies, and if we depend on something I'd like it in the FSharp namespace really.  Every time we've taken a dependency I've really really regretted it in the long term (that's for the FSF libraries).  This whole thing is just too much at the root of the universe.

So perhaps this could become `FSharp.Web.HtmlEngine` or something.   

That might lead to a longer discussion about where we put `FSharp` namespace libraries that we deem to be crtical, core and mature and really really really long term stable.

**Comment by Krzysztof-Cieslak** [comment]
That said, I’m not sure if I agree with outputting HTML from the ApiDocsModel part - this seems as fairly specific decision for something that can be used in many other ways, not just for generating HTML pages.

**Comment by dsyme** [comment]
> That said, I’m not sure if I agree with outputting HTML from the ApiDocsModel part - this seems as fairly specific decision for something that can be used in many other ways, not just for generating HTML pages.


Yeah I agree with this now I've thought it over

**Comment by dsyme** [comment]
I've done a round of improvements and the ApiDocsModel is now generating (a limited kind of) HTML fragments for formatted F# types, with hyperlinks for the type definitions involved.

It turns out the ApiDocsModel was already generating quite a lot of HTML from XML doc sections (both Markdown and XML docs).  Adding this additional generation seems reasonable - though I'd be happy to reveal this information in a different structured way (a HTML dom) - it would be an easy change to make

One issue is that whitespace sections in HTML are relevant to generating highlighted text for types like  `Foo<Goo<int>>` where Foo and Goo are hyperlinks.  This means the F# HTML DOMs need to not insert whitespacing in the relevant spans.  Currently a hack is being used o remove any whitespace and `&#32;` is used to generate spaces when they are needed
