### ISSUE TITLE
Problem when rendering one-line code blocks

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Formatting#56]
Hi,

I have a small sample code in my API docs:

![image](https://f.cloud.github.com/assets/57396/1419654/d7b65ff4-3fd0-11e3-915e-ad9051c7f570.png)

but somehow this is not rendered in a pre-tag:

![image](https://f.cloud.github.com/assets/57396/1419659/eceddc58-3fd0-11e3-9cc3-4adc86443c16.png)

**Comment by dsyme** [comment]
Closing this very old issue (partly because markdown docs are no longer being prioritised here - they are not yet an F# standard)
