### ISSUE TITLE
Why is there a binder badge in the index of the docs?

### ISSUE THREAD

**Issue by cartermp** [fsprojects/FSharp.Formatting#567]
It doesn't appear to do anything useful. When clicked, all it does is generate this:

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/6309070/89256653-75407700-d5d9-11ea-86cf-a6fa78497de6.png">

No examples, just some rendered HTML.

**Comment by dsyme** [comment]
Yes I was just testing things, it can be removed

It's the first line of https://github.com/fsprojects/FSharp.Formatting/blob/master/docs/index.md if you'd like to remove it :)

**Comment by dsyme** [comment]
Fixed
