### ISSUE TITLE
Dead link in upgrade docs

### ISSUE THREAD

**Issue by matthid** [fsprojects/FSharp.Formatting#576]
https://fsprojects.github.io/FSharp.Formatting/upgrade.html

Step 4 links `https://github.com/fsprojects/FSharp.Formatting/blob/master/misc/templates/_template.html` but the link is dead.

**Comment by dsyme** [comment]
cool thanks

**Comment by dsyme** [comment]
The foccrect link is https://github.com/fsprojects/FSharp.Formatting/blob/master/docs/_template.html

Though to be honest I'd encourage you not to copy over the default template yet, first read https://fsprojects.github.io/FSharp.Formatting/styling.html.  I've adjusted the upgrade docs accordingly

I understand FAKE uses its own styling and template though and you've done quite a lot of customization.  You probably do need to have your own template.  But I'd like to see that option used sparingly - only by projects that really need it - and where possible contribute back the template or theme to this repo so it can be maintained.

**Comment by dsyme** [comment]
Fixed in https://github.com/fsprojects/FSharp.Formatting/pull/578

**Comment by matthid** [comment]
> You probably do need to have your own template. But I'd like to see that option used sparingly - only by projects that really need it - and where possible contribute back the template or theme to this repo so it can be maintained.

One step at a time, when I kind of get the current docs kind of working with the new version I can take a look how that might work. There are several issues I have already encountered, which I need to do to get the new version up and running :(
