### ISSUE TITLE
[Feature] Multi-language support

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FSharp.Formatting#593]
F#F currently doesn't have a concept of the 'language' a particular page is authored in.  This means that in the case of a project like FCS,  the `/ja` content we have is rendered in the main navigation as additional top-level articles.

There should be a way to group the content by language, and render a 'picker' of some sort that would navigate the user to the same page in the chosen language, if present.

The navigation generated should be sensitive to the language chosen (ie for FCS if the user is on a `/ja/` page  only the Japanese content entries should be shown in the nav).

Soem systems allow for automatic language-classification of content by filename or directory path pattern (eg [Hugo](https://gohugo.io/content-management/multilingual/), [Jekyll](https://github.com/kurtsson/jekyll-multiple-languages-plugin)). Other systems take the approach of internationalizing specific segments of the content itself.

I think we need a model that allows for 

* seamless addition of new languages
* specification of content on a per-language basis (through some method like filename detection, folder detection, or explicit tagging in front-matter)
* grouping of the 'logically same' content across different languages.

Right now the actual processing of the content seems fine, it's mostly a grouping-level construct that we seem to be missing.

![image](https://user-images.githubusercontent.com/573979/90538496-3f0c0700-e144-11ea-8cb5-01711f2e4fed.png)

**Comment by baronfel** [comment]
A note: I'm working on converting the current FCS docs to use this tool in the dotnet/fsharp repository, which would then be incorporated into a build run to help ensure correctness of the docs as the FCS from that repo changes. This is in service of the goal of publishing FCS from that repo entirely.

**Comment by dsyme** [comment]
It's odd that the hardest part of doc generation is the table of contents and/or navigation.  I wonder if we should just accept a `_navigation.md` in each directory that gives the preferred navigation active in that folder as a markdown document

**Comment by dsyme** [comment]
I added a heuristic that two-letter directory names like `ja` are suppressed from the main table of contents.  I think that's good enough for now.   It's in the docs https://fsprojects.github.io/FSharp.Formatting/content.html#Multi-language-Content
