### ISSUE TITLE
API Reference docs generation is broken

### ISSUE THREAD

**Issue by deviousasti** [fsprojects/FSharp.Formatting#607]
The API reference page is blanked out when generating docs.
It's present in `FSharp.Formatting`'s own docs at:

https://fsprojects.github.io/FSharp.Formatting/reference/index.html

**Comment by dsyme** [comment]
sigh :-)  Will look into it

**Comment by dsyme** [comment]
This is a big motivator for https://github.com/fsprojects/FSharp.Formatting/issues/604

**Comment by dsyme** [comment]
Fixed thanks.

The problem was the docs were being built against debug binaries, but only release had been built

fsdocs now supports `--strict` and `--property` e.g.

```
fsdocs build --clean --strict --property Configuration=Release
``


https://fsprojects.github.io/FSharp.Formatting/commandline.html
