### ISSUE TITLE
FSharp.Formatting.fsx fails because Log is now internal

### ISSUE THREAD

**Issue by thinkbeforecoding** [fsprojects/FSharp.Formatting#609]
When loading the FSharp.Formatting.fsx with #load in scripts, the execution fails because the scripts use FSharp.Formatting.Common.Log that is now internal.

**Comment by thinkbeforecoding** [comment]
A solution is to not use the fsx... but...
The fastest way to use the nuget in a script is with Paket using generate_load_scripts, which automatically execute the fsx...

**Comment by wallymathieu** [comment]
Is this fixed by the pull request?

**Comment by thinkbeforecoding** [comment]
Yes it is

**Comment by wallymathieu** [comment]
I'm cclosing the issue then 😄
