### ISSUE TITLE
Ability to output a raw string from an FSI evalutation instead of having it wrapped in code blocks

### ISSUE THREAD

**Issue by HLWeil** [fsprojects/FSharp.Formatting#611]
Hey, is it possible to somehow use a custom `fsiEvaluator` when running `dotnet fsdocs build`?

**Comment by dsyme** [comment]
> Hey, is it possible to somehow use a custom fsiEvaluator when running dotnet fsdocs build?

No.  This kind of parameterization sits very awkwardly with a command line tool

What specifically are you looking for ?  I never fully understood the use cases for custom evaluators, given the complexity they bring

**Comment by HLWeil** [comment]
Thanks for your answer.

I'm looking for embedding Plotly charts like we did [here](https://csbiology.github.io/FSharp.Stats/#Regression).

**Comment by HLWeil** [comment]
Sry my description was very unspecific. 
My problem is, that even when I try a workaround like piping the chart into a function which returns a finished html string, this string then gets inserted intro `<pre>`  tags, preventing the chart to be rendered. In our own build script, we used an FSI evaluator which did not create this tag when given a chart. But using the new command line tools seems much more lightweight and easily manageable so we would like to migrate.

I understand that using the custom evaluator with the tools is not doable. So the follow up question would be: Is it possible to prevent the standard evaluator from packing the evaluated result into `<pre>` tags?

**Comment by dsyme** [comment]
OK I see. Yes we can address this somehow

However I'd really appreciate step by step instructions about which charting library etc. Exact step by step please, including actual and expected results

**Comment by HLWeil** [comment]
## Reproduction
I created a repo for illucidating my problem: https://github.com/HLWeil/FsDocsEvaluatedCharts

The repro steps are described there. The created `output/ChartTest.html` is the file of interest. In this file three ways to embed a chart are displayed:

1.  `Include Chart directly` (Using a custom FsiEvaluator; Undoable)

2. `Include Evaluated HTML string` (Using an additional function)

3.  `HTML String` (Include the chart html **by hand**; Just for showcase purposes)

## Desired result

The chart html gets correctly formatted not only in the third, but also in the second case.

## Actual result

The chart html does not get formatted correctly but as a code snippet. This is because the standard FsiEvaluator inserts the evaluated result into `<code>` and `<pre>` tags.

## Possible solution

Maybe it is possible to offer a `literate command` which does not encapsulate the evaluated result into tags. This could e.g. be called `(***include-inline***)`.

**Comment by adz** [comment]
FSharpPlus has a plantuml based diagram - it works by generating a diagram from a local text-file. The diagram is encoded into an url that uses www.plantuml.com/plantuml to generate the actual graphic. We currently manually inject this url as a post-processing step:
https://github.com/fsprojects/FSharpPlus/blob/master/docsrc/tools/Program.fs#L160

The call to_url is from Plantuml module:
https://github.com/fsprojects/FSharpPlus/blob/master/docsrc/tools/templates/plantuml.fs#L8

which then replaces {plantUMLDiag} here:
https://github.com/fsprojects/FSharpPlus/blob/master/docsrc/content/abstractions.fsx#L15

producing:
https://fsprojects.github.io/FSharpPlus/abstractions.html

I'm moving it over to use the fsdocs cmd, and am looking for a way to do this. Might be another use case?
