### ISSUE TITLE
Live refresh/Hot reload

### ISSUE THREAD

**Issue by kMutagene** [fsprojects/FSharp.Formatting#627]
Currently, when developing docs via `fsdocs watch`, one has to manually reload the browser page after the new files are generated. As this project uses Suave, it should be possible to mirror the changes of [this PR](https://github.com/ionide/Fornax/pull/29) to fornax, which implemented live refresh there.

**Comment by dsyme** [comment]
Sounds good

Kevin, I think I should make you Co admin on this repot and nuget (I'm on vacation and haven't republished the nuget yet)

**Comment by dsyme** [comment]
Kevin, what's your nuget id please?

**Comment by kMutagene** [comment]
I'll be glad to help where I can, sorry to have bothered you during vacation, enjoy the rest of it ;). My nuget profile is here: https://www.nuget.org/profiles/Mutagene.

**Comment by dsyme** [comment]
@kMutagene I've sent the request on github

**Comment by kMutagene** [comment]
@dsyme thank you! I was just writing the release docs for the next package (feels a little strange to write those about commits that are not my own) and wondering about #621 and how that commit affects the version number of the next package, will it be 8.0 or 7.3? When that is sorted i will release the package today

**Comment by dsyme** [comment]
@kMutagene When in doubt bump the major version :-)

**Comment by kMutagene** [comment]
Closed as of #629
