### ISSUE TITLE
Keep ids in generated html constant if possible

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Formatting#63]
Hi,

I use gh-pages workflow which commits all generated docs into the gh-pages branch. Every commit looks like this

![image](https://f.cloud.github.com/assets/57396/1474371/ca3cf51a-462c-11e3-894d-49e649a2c13f.png)

**Comment by dsyme** [comment]
I'm seeing more id consistency in the generated docs

But in any case this is old enough that I'm closing it as won't fix
