### ISSUE TITLE
FSharp.Formatting.Razor reference update?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/FSharp.Formatting#648]
Could the package [FSharp.Formatting.Razor](https://www.nuget.org/packages/FSharp.Formatting.Razor/)
dependencies be updated or relaxed please, 
to have [RazorEngine.NetCore](https://www.nuget.org/packages/RazorEngine.NetCore/) reference 3.1.0?
Also same thing, the dependency to [Microsoft.AspNetCore.Razor.Language](https://www.nuget.org/packages/Microsoft.AspNetCore.Razor.Language/6.0.0-preview.1.21103.6).

**Comment by Thorium** [comment]
I know you may have moved away from Razor, however there is a lot of libraries having documentation generated with old generate.fsx which causes now maintenance issues as there is no migration documentation to upgrade that. At least I couldn't find one with Google.

**Comment by dsyme** [comment]
Razor isn't somethig we're looking a returning to.

There's an upgrade doc of sorts here https://fsprojects.github.io/FSharp.Formatting/upgrade.html

The generate.fsx files are like poison and should never have been allowed to proliferate.  Just delete them and start your docs over based on content and styling alone.

**Comment by Thorium** [comment]
I've updated a few project documentations today, and I have to say the experience was less painful what I expected.
