### ISSUE TITLE
Cannot install NuGet package targeting Xamarin.Mac,Version=v2.0

### ISSUE THREAD

**Issue by twop** [fsprojects/FSharp.Formatting#655]
Error I when I try to install the package for Xamarin Mac project (I use Fabulous).

> Could not install package 'Microsoft.Win32.Registry 4.3.0'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Note that `Microsoft.Win32.Registry 4.3.0` was not present in version 7.2.9 and appeared in 8.0.0

I installed 7.2.9 but it messes up with live reloading because it is compiled with a different version of F#

Note: I only need  `FSharp.Formatting.Markdown.dll`, so I will try to reference it directly but it seems awkward not being able to install NuGet Package

Thanks <3

**Comment by dsyme** [comment]
This project doesn't support Xamarin.Mac
