### ISSUE TITLE
fsdocs-source-filename etc

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Formatting#658]
From @gbaydin 

There are places where having a substitution for the relative source filename would be helpful, e.g. https://github.com/DiffSharp/DiffSharp/blob/dev/docs/documentation-extensions.fsx#L19

Something like this

    fsdocs-source-filename -->  foo/example.fsx
    fsdocs-source-filename-without-extension -->  foo/example

This saves error prone repetitive substitutions.

**Comment by gbaydin** [comment]
It looks like the relevant code is [here](https://github.com/fsprojects/FSharp.Formatting/blob/83789ef1d12a8d8d34045499b6f74b583e78338b/src/FSharp.Formatting.Literate/Formatting.fs#L71)

**Comment by dsyme** [comment]
Available in fsdocs 10.0.1

**Comment by gbaydin** [comment]
Awesome :)
