### ISSUE TITLE
Flag --noapidocs does not prevent project cracking

### ISSUE THREAD

**Issue by Joott** [fsprojects/FSharp.Formatting#669]
When running the command `dotnet fsdocs watch --eval --noapidocs` in a repository that contains .fsproj files, the tool still attempts to crack the projects for API docs. In a repository that contains no library projects or no projects with `<GenerateDocumentationFile>true</GenerateDocumentationFile>` set, this results in every project being skipped which leads to an error.

![image](https://user-images.githubusercontent.com/39764934/115751614-a47e5a80-a399-11eb-912e-bed46a31cbba.png)

The docs in the `docs` folder could theoretically still be built, since the .fsproj files are not needed. Wouldn't it make more sense to skip the cracking of the projects as well instead of only the writing of the API docs when the flag `--noapidocs` is set?

**Comment by dsyme** [comment]
> In a repository that contains no library projects or no projects with `<GenerateDocumentationFile>true</GenerateDocumentationFile>` set, this results in every project being skipped which leads to an error.

This seems wrong, yes, even without `--noapidocs`

Please take a look around here if you'd like to submit a fix https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.Formatting.CommandTool/ProjectCracker.fs#L347

**Comment by Joott** [comment]
I made a pull request (#670), which changes the error to a warning and removes the exit function. This way, the building of the docs will not fail when no projects could be cracked, with or without `--noapidocs` set. With `--strict` set it fails in either case.
I also have a proposal for an additional solution (https://github.com/Joott/FSharp.Formatting/commit/f912d5f2e3327055e55632887884a1cbbeba34d5) to this problem: The introduction of the `--ignoreprojects` flag. When this flag is set, the list of project files is set to an empty list, which skips all the steps of project cracking. Additionally, it only fails for no cracked projects with `--strict` when `--ignoreprojects` is false, so this option could be used together with `--strict`.

**Comment by dsyme** [comment]
I merged #670.  

> I also have a proposal for an additional solution (Joott@f912d5f) to this problem: The introduction of the --ignoreprojects flag. When this flag is set, the list of project files is set to an empty list, which skips all the steps of project cracking. Additionally, it only fails for no cracked projects with --strict when --ignoreprojects is false, so this option could be used together with --strict.

This is also ok if you'd like to submit that

**Comment by Joott** [comment]
Thank you! I created a pull request which introduces the --ignoreprojects flag.

**Comment by dsyme** [comment]
Thanks for the contribution!
