### ISSUE TITLE
Menu is not scrollable on mobile

### ISSUE THREAD

**Issue by nhirschey** [fsprojects/FSharp.Formatting#672]
Following up on comment here https://github.com/fsprojects/FSharp.Data/pull/1370#issuecomment-820428350

Summary: if you’re on a mobile browser then clicking the sidebar/hamburger on the current template fills the browser window with the sidebar, and that sidebar menu that pops out is not scrollable. So it’s impossible (at least on iOS) to scroll to and click on links at the bottom of the side bar. You’re restricted to the first few items on the sidebar. In the screenshot in the above linked FSharp.Data comment, I can’t access anything below XML Provider.

**Comment by dsyme** [comment]
Thanks for the fix!

**Comment by dsyme** [comment]
@nhirschey Scrollable navbar looks a bit off for desktop, see

https://fsprojects.github.io/FSharp.Formatting/

![image](https://user-images.githubusercontent.com/7204669/126667262-cd79bb57-29e2-48df-bf3b-67f56baae7dd.png)

**Comment by nhirschey** [comment]
Ok, I will see if I can find a way to expand it so that it fills the vertical real estate on desktop. In your screenshot the scrollbar isn’t needed.

**Comment by nhirschey** [comment]
Pull request #689 is the most minimal change to the template that
1. Has no navbar scrollbar on desktop when there is sufficient vertical space to display all navbar items.
2. Makes the navbar usable on mobile browsers (by adding a scrollbar, see https://github.com/fsprojects/FSharp.Data/pull/1370#issuecomment-820428350 for a description of the problem).

That said, the current navbar in the FSharp.Formatting template could probably be simplified. I will experiment as I have time.

**Comment by dsyme** [comment]
Thank you! that's great
