### ISSUE TITLE
Showing type denotation for record fields

### ISSUE THREAD

**Issue by chengh42** [fsprojects/FSharp.Formatting#674]
Hi, thanks for the fantastic package! We enjoy very much using FSharp.Formatting for making our package documentations :)

One feature that we're wondering though, is it possible to show also the type denotations for record fields?

Would appreciate any help or a bit of guidance on making it work - in case it's a feature that's already available.

## Example

For instance, with the record type `UnicornRecord`,

```fsharp
/// Template for creating unicorns.
type UnicornRecord = {
    /// Its unique name.
    Name : string
    /// How old is this creature?
    Age  : int
}
```

... the generated reference doc is,

  > ## UnicornRecord Type
  > 
  > Namespace: ...
  > Assembly: ...
  > Base Type: ...
  > All Interfaces: ...
  > 
  > #### Template for creating unicorns.
  > 
  > ### Record fields 
  > | Record Field | Description |
  > | --  | -- |
  > | Name  | Its unique name. |
  > | Age     | How old is this creature? |

Currently, when hover over `Name` it shows a tooltip saying "Full usage: Name". Would it be possible to have the type denoted in it too (in this case, `string`)? Would be super useful.

Thanks! (May be also willing to contribute to a pull request but will need some guidance on this :)

cc @Lewiszz @Janna112358

**Comment by dsyme** [comment]
Yes it should be possible. The renderMembers for fields is here (for markdown generation): https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.Formatting.ApiDocs/GenerateMarkdown.fs#L274

As comparison you can see a return type get emitted here: https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.Formatting.ApiDocs/GenerateMarkdown.fs#L84


For FSharpField the return type is 'None' https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L1312. You likely want to populate that starting with the FSharp.Compiler.Service field type, similar to how it's done here for method return types https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L1234

**Comment by chengh42** [comment]
Thanks a lot for the instructions! Super useful!

With the pull request #676 rendered doc comes with type notation for record fields. Example taken from FSharp.Formatting.Markdown `MarkdownRange` record type:

![image](https://user-images.githubusercontent.com/44002425/117174894-84558f00-adce-11eb-8cdb-98bebbcde364.png)
