### ISSUE TITLE
Cache needs removing if <PackageProjectUrl> is edited

### ISSUE THREAD

**Issue by davedawkins** [fsprojects/FSharp.Formatting#692]
To reproduce:
1. Run `fsdocs build`
2. Note value of `root` in output log under `Substitutions/parameters`
3. Edit value of `<PackageProjectUrl>`
4. Re-run `fsdocs build`
5. Note value of `root` hasn't changed (it should have value used in step 3 though)
6. Remove `.fsdocs/cache`
7. Re-run `fsdocs build`
8. Note value 'root' now reflects value of `<PackageProjectUrl>`

Eg. Edited .fsproj file
```
    <PackageProjectUrl>https://pkgurl/abc1</PackageProjectUrl>
```

Output from `fsdocs build`
```
david@davebook Sutil % dotnet fsdocs build --output public/docs  |more
restored project state from '.fsdocs/cache'

Inputs for API Docs:
    /Users/david/projects/Sutil/src/Sutil/bin/Debug/netstandard2.0/Sutil.dll

Substitutions/parameters:
  root --> https://pkgurl/abc/
```

**Comment by davedawkins** [comment]
I'll attempt a PR for this

**Comment by davedawkins** [comment]
PR incoming...

**Comment by dsyme** [comment]
@davedawkins Did you send a PR for this?

**Comment by davedawkins** [comment]
I appear to have committed to my own fork and then not progressed to sending a PR. Investigating...

**Comment by davedawkins** [comment]
OK I worked out what happened. I did submit a PR, then realized it could be replaced with a doc update, and we closed the PR. See https://github.com/fsprojects/FSharp.Formatting/pull/698

**Comment by dsyme** [comment]
Cool, thank you for checking!
