### ISSUE TITLE
Including snippet output by name does not work.

### ISSUE THREAD

**Issue by DavideGCosta** [fsprojects/FSharp.Formatting#694]
I may be getting the syntax wrong, but I think that this example should show versions of ` val it : int = 4 ` as output but I am instead getting errors. 

```fsharp
(**
Including snippet output by name does not work.
*)
(*** define: answer ***)
2 + 2
 
(*** include: answer ***)
 
(*** include-output: answer ***)
(*** include-fsi-output: answer ***)
(*** include-fsi-merged-output: answer ***)
(*** include-it: answer***)
(*** include-it-raw: answer ***)
 
(*** include: answer ***)
```

HTML Example:
<img width="1128" alt="Screenshot 2021-07-29 at 16 59 41" src="https://user-images.githubusercontent.com/83724795/127525618-41003aa3-789e-4d5b-becb-5a7370af97ad.png">

**Comment by nhirschey** [comment]
The documentation section that says this should be possible is here https://fsprojects.github.io/FSharp.Formatting/literate.html#Named-snippets

**Comment by dsyme** [comment]
From the tests it looks like it's 
```
(*** define-output:test ***)
```

**Comment by dsyme** [comment]
I'll fix the docs

**Comment by dsyme** [comment]
I think the docs are correct now, please double check? https://fsprojects.github.io/FSharp.Formatting/literate.html#Naming-and-including-snippets

**Comment by DavideGCosta** [comment]
Thanks, @dsyme! 
The docs seem to be correct.
