### ISSUE TITLE
Download script links in docs broken

### ISSUE THREAD

**Issue by olivercoad** [fsprojects/FSharp.Formatting#696]
The download script links in the docs lead to gh pages 404.

For example on https://fsprojects.github.io/FSharp.Formatting/content.html it links to https://fsprojects.github.io/FSharp.Formatting/content.fsx which is a 404 page.

The fsx scripts don't exist on the `gh-pages` branch. Either the fsx files should be copied into the gh-pages build or it could link directly to the source file on github, ideally with the git commit sha that that doc was built from, such as https://github.com/fsprojects/FSharp.Formatting/blob/49ee266b0d5c2cb3baa468add69b4439a39dea6f/docs/content.fsx

**Comment by dsyme** [comment]
Looks like `_template.fsx` was missing, added now, thanks!

https://github.com/fsprojects/FSharp.Formatting/commit/364e6c14d64d0491178a0b76f9f95df3ff8707da

**Comment by dsyme** [comment]
Cool this is fixed, thanks for the report!

**Comment by olivercoad** [comment]
Is the downloaded file meant to be empty? https://fsprojects.github.io/FSharp.Formatting/content.fsx now seems be just a single line feed character.

**Comment by dsyme** [comment]
Really fixed now :)
