### ISSUE TITLE
doc generation not failing when using the `--strict` flag

### ISSUE THREAD

**Issue by kMutagene** [fsprojects/FSharp.Formatting#700]
It may be a misinterpretation from my side, but from the docs:

> --strict | Fail if docs are missing or can't be generated

It seems like this is not the case, as doc generation goes on after a script failed. Here is an example output from 

`fsdocs build --eval --clean --properties Configuration=Release --parameters fsdocs-package-version 2.0.0 --strict`

In Plotly.NET:

```
generating model for docs\1_0_axis-styling.fsx --> .\1_0_axis-styling.html
   docs\1_0_axis-styling.fsx: error(67,8)-(67,16) The member or object constructor 'init' has no argument or settable return ... <OMITTED FOR BREVITY>
  generating model for docs\1_1_errorbars.fsx --> .\1_1_errorbars.html
  generating model for docs\1_1_errorbars.fsx --> .\1_1_errorbars.ipynb
  generating model for docs\1_1_errorbars.fsx --> .\1_1_errorbars.fsx
```

So does this mean that we are failing on a per-file basis? if so, i'd suggest another flag like `--fail-fast` to stop the whole process if a script fails.

This is also more CI-friendly, as broken docs would not get pushed if they are built and released in a pipeline.

**Comment by dsyme** [comment]
Yes, agreed, these should fail the doc build

**Comment by dsyme** [comment]
Fixed by https://github.com/fsprojects/FSharp.Formatting/pull/729

**Comment by dsyme** [comment]
Fixed
