### ISSUE TITLE
ConvertScriptFile/fsdocs silently ignores nuget errors

### ISSUE THREAD

**Issue by catfly1** [fsprojects/FSharp.Formatting#703]
It seems that .fsx reference issues don't correctly bubble up to the output of fsdocs, making it nearly impossible to debug. This feels like dejavu and I'm sure I've hit this before.

Steps to reproduce:

```
$ mkdir -p /tmp/test/docs
$ cd /tmp/test 
$ echo '#r "nuget: oasdifja"' > docs/test.fsx
$ dotnet new tool --force
$ dotnet tool install FSharp.Formatting.CommandTool
$ dotnet fsdocs build --eval --noapidocs --strict
```

**Result**: `output/test.html` is generated.
**Expected**: command should fail with 'unable to find package oasdifja', consistent with `dotnet fsi -i docs/test.fsx`
**Env**: 5.0.400 on Debian Linux.
**Workaround**: create csproj in a bootstrap directory with the packages and publish to known dir before running fsdocs.

Additionally tried the following (nothing was printed) with:
```
let fsi = FsiEvaluator(discardStdOut=false)
fsi.EvaluationFailed.AddHandler((fun x args -> printfn "Failed:%A" args))

Literate.ConvertScriptFile("docs/test.fsx", "docs/_template.html", fsiEvaluator = fsi, references=true)
```

**Comment by dsyme** [comment]
Fixed in https://github.com/fsprojects/FSharp.Formatting/pull/729
