### ISSUE TITLE
I think that we should remove the examples from the tooltips

### ISSUE THREAD

**Issue by MecuSorin** [fsprojects/FSharp.Formatting#706]
The tooltips are bloated by examples. Maybe just refer examples as a single link in the tooltips

![image](https://user-images.githubusercontent.com/2384174/132940262-793d0d2c-5314-47d0-9b56-69a25f7b4997.png)
![image](https://user-images.githubusercontent.com/2384174/132940296-0378b992-9733-4eb9-a56b-8a0a39812b0d.png)

**Comment by dsyme** [comment]
Agreed!

**Comment by dsyme** [comment]
Are those tooltips in Ionide or FSharp.Formatting doc pages?

**Comment by baronfel** [comment]
Those look a lot like Ionide, and so would be in the TipFormatter.fs file in the FsAutoComplete.Core project. We'd have to make sure that only tooltips were impacted by such a change.

**Comment by dsyme** [comment]
This is an Ionide thing
