### ISSUE TITLE
Using `--input .` ends up creating an infinite loop

### ISSUE THREAD

**Issue by mlaily** [fsprojects/FSharp.Formatting#709]
Hi!

For a long time now I have been kind of impressed by all the interactive F# code one can find on the web, so I wanted to try `FSharp.Formatting` for the first time today, hoping I could quickly get simple interactive html from an fsx script, ready to import in a blog post.

After fumbling some times with the command line, and trying to find some documentation for my use case, I realized the command I was using — `dotnet fsdocs watch --ignoreprojects --input .` — was stuck, recursively creating nested temporary folders!

By the time I forcibly stopped it, I had more than 250 nested folders, that I then had to delete using `shift + del` because Windows wouldn't let me do it the normal way.

In the end I managed to get the tool to work and get what I wanted by scaffolding a template and fiddling some more.

I guess my use case for a quick one-off usage is not directly supported (sadly), and this is partly my fault for trying to use this tool in a way it was not designed to, but I thought I would submit an issue anyway.

I figure first-use feedback might interest you, and it's probably not too hard to prevent the infinite loop in this scenario, so if it can help future users...

**Comment by dsyme** [comment]
It's a nice use case, it would be good if it worked.  Did you try just putting your script in a "docs" subdirectory?

**Comment by mlaily** [comment]
> 
> 
> It's a nice use case, it would be good if it worked. Did you try just putting your script in a "docs" subdirectory?

That's what I ended up doing, but it does not feel natural for me to have my code in a "docs" directory... and since everything is so tightly integrated together, it's harder than I wish it were to extract only the relevant part from the generated files.

(I did not want to bring it up, but another issue is that unless I create an "index.fsx", the `fsdocs watch` command opens my browser with a page that does not load)

**Comment by nhirschey** [comment]
I have encountered these things before. Allowing --input to work with a single file is something on my "todo" list to try to contribute : )

Some workarounds:

> hoping I could quickly get simple interactive html from an fsx script, ready to import in a blog post.

You might try the fsiEvaluator documented as [FSharp.Formatting as a library](https://fsprojects.github.io/FSharp.Formatting/evaluation.html#F-Formatting-as-a-Library-Custom-formatting-functions)

```fsharp
#r "nuget: FSharp.Formatting"

open FSharp.Formatting.Literate
open FSharp.Formatting.Literate.Evaluation

let listy = """
### Formatting demo
let test = ["one";"two";"three"]
(*** include-value:test ***)"""

let fsi = FsiEvaluator()
let docOl = Literate.ParseScriptString(listy, fsiEvaluator = fsi)
Literate.ToHtml(docOl)
```
```
val it : string =
  "<table class="pre"><tr><td class="lines"><pre class="fssnip"><span class="l">1: </span>
<span class="l">2: </span>
</pre></td>
<td class="snippet"><pre class="fssnip highlighted"><code lang="fsharp"><span class="pn">#</span><span class="pn">#</span> <span class="id">Formatting</span> <span class="id">demo</span>
<span class="k">let</span> <span onmouseout="hideTip(event, 'fs1', 1)" onmouseover="showTip(event, 'fs1', 1)" class="id">test</span> <span class="o">=</span> <span class="pn">[</span><span class="s">&quot;one&quot;</span><span class="pn">;</span><span class="s">&quot;two&quot;</span><span class="pn">;</span><span class="s">&quot;three&quot;</span><span class="pn">]</span>
</code></pre></td>
</tr>
</table>
<table class="pre"><tr><td><pre><code>No value returned by any evaluator</code></pre></td></tr></table>
<div class="fsdocs-tip" id="fs1">val test : string list</div>

"
```

> it does not feel natural for me to have my code in a "docs" directory

`--input` could be any directory.

> another issue is that unless I create an "index.fsx", the fsdocs watch command opens my browser with a page that does not load)

When this happens because you don't have an index, if your script is named "script.fsx" go to script.html and it will work.

![docstest](https://user-images.githubusercontent.com/5226115/135725182-d50fcad9-294e-4cba-9e0e-322f941ccdf0.gif)

**Comment by mlaily** [comment]
@nhirschey thanks for the fsiEvaluator script! It looks easier to use than what I anticipated.

I am aware the other problems I mentioned have workarounds, but thanks for taking the time to document them anyway :)
