### ISSUE TITLE
How can we access the Raw doc comments?

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/FSharp.Formatting#710]
The `ApiDocComment` has a property [RawData](https://fsprojects.github.io/FSharp.Formatting/reference/fsharp-formatting-apidocs-apidoccomment.html#RawData) but this property is returning an already processed XML content.

For me, the returned information is not really usable for 2 reasons:

1. It is removing some of the content from the XML for example the `example` content has been removed
2. It modify the structure of the XML, see the `para-0`, `para-1`, `para-2`. I have no way of knowing where they where inside the XML

```fs
/// <summary>
/// <para>Represents the context of a page within Nacara.</para>
/// <para>It contains all the information available for the specified page like it's title, layout, etc.</para>
/// </summary>
/// <remarks>
/// <para>It contains all the information available for the specified page like it's title, layout, etc.</para>
/// <example>
/// blabla
/// </example>
/// </remarks>
```

gives:

```
[[summary, Represents the context of a page within Nacara.It contains all the information available for the specified page like it's title, layout, etc.];
 [remarks, It contains all the information available for the specified page like it's title, layout, etc.
 blabla
 ];
 [para-0, Represents the context of a page within Nacara.];
 [para-1, It contains all the information available for the specified page like it's title, layout, etc.];
 [para-2, It contains all the information available for the specified page like it's title, layout, etc.]]
```

I also tried to use the [Symbol](https://fsprojects.github.io/FSharp.Formatting/reference/fsharp-formatting-apidocs-apidocentity.html#Symbol) property from `ApiDocEntity` but when calling `GetXmlText()` or `UnprocessedLines` it returns nothing.

```fs
let renderRecord (info : ApiDocEntityInfo) =
    let entity = info.Entity

    match entity.Symbol.XmlDoc with
    | FSharpXmlDoc.FromXmlFile (dllName, xmlSig) ->
        printfn "%A" dllName
        printfn "%A" xmlSig

    | FSharpXmlDoc.FromXmlText xmlDoc ->
        printfn "%A" entity.Name
        printfn "Doc FromText: %A" (xmlDoc.GetXmlText())
        printfn "Doc FromText: %A" (xmlDoc.UnprocessedLines)

    | FSharpXmlDoc.None ->
        printfn "Note doc found"
```

This gives:

```
"PageContext"
Doc FromText: ""
Doc FromText: [||]
```

for this F# code:

```fs
/// <summary>
/// <para>Represents the context of a page within Nacara.</para>
/// <para>It contains all the information available for the specified page like it's title, layout, etc.</para>
/// </summary>
/// <remarks>
/// <para>It contains all the information available for the specified page like it's title, layout, etc.</para>
/// <example>
/// blabla
/// </example>
/// </remarks>
[<NoComparison>]
type PageContext =
    {
        PageId : string
    }
```

**Comment by MangelMaxime** [comment]
Another things that I find strange is that I have provided the `.dll` file as input with the documentation extracted to the XML files but it says that the documentation has been found `FromXmlText` instead of `FromXmlFile`.

I used `dotnet publish` to generates the `.dll` serving as the entry point.

**Comment by dsyme** [comment]
@MangelMaxime It seems we can provide the `XElement` from the lookup in the XML file fairly easily, for those XML doc drawn from there

**Comment by dsyme** [comment]
.Xml now available as an XElement, I trust it's enough.
