### ISSUE TITLE
FSharp.Formatting package contains MSBuild assemblies

### ISSUE THREAD

**Issue by rainersigwald** [fsprojects/FSharp.Formatting#714]
While helping investigate test failures in https://github.com/fsharp/FsAutoComplete/pull/825, I noticed that FSharp.Formatting contains several MSBuild assemblies:

* Microsoft.Build.Framework.dll
* Microsoft.Build.Tasks.Core.dll
* Microsoft.Build.Utilities.Core.dll
* Microsoft.NET.StringTools.dll

That caused some surprising behavior, since MSBuild assemblies need to be located from Visual Studio or a .NET SDK rather than redistributed with an application, because of their entanglement with targets and tasks that are part of the SDK. [MSBuildLocator docs](https://docs.microsoft.com/visualstudio/msbuild/updating-an-existing-application?view=vs-2019) have some details.

Can those files be elided from the package?

**Comment by nhirschey** [comment]
Closed with https://github.com/fsprojects/FSharp.Formatting/pull/715
