### ISSUE TITLE
fsharp.formatting.commandtool has been renamed to fsdocs-tool

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Formatting#720]
Thie nuget has been renamed.  

https://www.nuget.org/packages/FSharp.Formatting.CommandTool/

it is now

https://www.nuget.org/packages/fsdocs-tool

**Comment by teo-tsirpanis** [comment]
Can you mark `FSharp.Formatting.CommandTool` as [deprecated](https://docs.microsoft.com/en-us/nuget/nuget-org/deprecate-packages) to more visibly guide users to `fsdocs-tool`?

**Comment by dsyme** [comment]
Done, thanks!  I didn't know about package deprecation

**Comment by 64J0** [comment]
Is there some documentation on how to migrate projects using the deprecated package to use the new one?

**Comment by teo-tsirpanis** [comment]
I think you just have to change the package name.

**Comment by 64J0** [comment]
No, the versions are incompatible. I found a project using `fsharp.formatting.commandtool` version `11.4.4`. `fsdocs-tool` does not have this version. I'm trying with version `12.0.0` instead.

**Comment by teo-tsirpanis** [comment]
You have to update the version as well. `fsharp.formatting.commandtool` and `fsdocs-tool` are fundamentally the same software. New versions of it have stopped being released on the former, but will be on the latter.

**Comment by 64J0** [comment]
I see, thanks for the explanation @teo-tsirpanis, now I understood 👍🏼
