### ISSUE TITLE
Can we remove FSharp.Compiler.Service for markdown package

### ISSUE THREAD

**Issue by albertwoo** [fsprojects/FSharp.Formatting#730]
The FSharp.Compiler.Service is too big (30MB)

**Comment by dsyme** [comment]
No, sorry, that's not a goal of this repo.  This repo is about formatting F# code and documentation and is not a generic markdown library.

**Comment by albertwoo** [comment]
Ok, the aternertive is https://github.com/xoofx/markdig

**Comment by dsyme** [comment]
Yes, that library looks great
