### ISSUE TITLE
Can we enforce the required version of FCS ?

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/FSharp.Formatting#731]
When upgrading to v14.0.1, to get access to the XML doc comment I had this is error:

> Could not read comments from entity 'Ws.WebSocketStatic.CLOSED': System.MissingMethodException: Method not found: 'Boolean FSharp.Compiler.Syntax.PrettyNaming.IsOperatorName(System.String)'.
   at FSharp.Formatting.ApiDocs.SymbolReader.readMemberOrVal(ReadingContext ctx, FSharpMemberOrFunctionOrValue v)
   at FSharp.Formatting.ApiDocs.SymbolReader.tryReadMember@2516.Invoke(String cat, Int32 catidx, Boolean exclude, IDictionary`2 _arg1, ApiDocComment comment)
   at FSharp.Formatting.ApiDocs.SymbolReader.readCommentsInto$cont@2455[c](FSharpSymbol sym, FSharpFunc`2 f, FSharpOption`1 nsdocs, ApiDocComment comment, IDictionary`2 cmds, String cat, Unit unitVar)

It seems like this error is coming from the fact that I upgraded FCS at the same time to version 41.0.1.

![image](https://user-images.githubusercontent.com/4760796/141791725-ed0748c5-fb32-480e-865e-ecf359d8f450.png)

Should FSharp.Formatting be more strict in it's dependencies constraints on Nuget?

**Comment by MangelMaxime** [comment]
However I'm not sure why I have FCS as dependencies on my side, as it should be installed with F# Formatting by default.

Perhaps, this is a remainder of when I was experimenting for Nacara.GenApi. I will try removing it this evening and see if things still compiles

**Comment by dsyme** [comment]
@MangelMaxime Yes it looks like your paket resolution has bumped FCS up to 41, but 40 is requried and they are not binary compatible.   

Is it possible for the FCS package to declare that future major versions of it will not be binary compatible?  If that's possible I don't know the magic foo necessary.

**Comment by MangelMaxime** [comment]
Pinning FCS does fix the problem indeed.

> Is it possible for the FCS package to declare that future major versions of it will not be binary compatible?

I don't think you can do that, but I think on NuGet it is possible to say that we want latest version of FCS 40.*. 

https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#floating-versions

However, I am not sure if Paket allows to specific this kind of floating versions.

Feel free to close this issue, if you think no action is required on F# Formatting side.

**Comment by dsyme** [comment]
Thanks!
