### ISSUE TITLE
v15.0.0 gives --multiemit warnings when accessing types defined in prior snippets

### ISSUE THREAD

**Issue by nhirschey** [fsprojects/FSharp.Formatting#740]
It looks like changes for fsi script debugging in .net6.0 (https://github.com/dotnet/fsharp/pull/12722) are causing multi-emit warnings in v15 versions of fsdocs-tool.

To reproduce, I create a blank docs folder and add index.fsx with this:

```fsharp

type Test = { A: int; B: string }


let list = [{ A = 1; B = "a" }; { A = 2; B = "b" }; { A = 3; B = "c" }]
[ for x in list do x.A ]

(***include-fsi-output***)

[ for x in list do x ]
(***include-fsi-output***)

[ for x in list do x.A ]
(***include-fsi-output***)
```

When I run `dotnet fsdocs watch --eval` I get this below.  Note the warning in the last snippet, with full text 
> input.fsx (1,1)-(1,25) interactive warning Accessing the internal type, method or field 'A@' from a previous evaluation in F# Interactive is deprecated and may cause subsequent access errors. To enable the legacy generation of a single dynamic assembly that can access internals, use the '--multiemit-' option."

<img width="474" alt="image" src="https://user-images.githubusercontent.com/5226115/159949913-b84389ed-184d-4555-8ed2-2f032e52c83e.png">

## Tools info

```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "fsdocs-tool": {
      "version": "15.0.0",
      "commands": [
        "fsdocs"
      ]
    }
  }
}
```

**Comment by dsyme** [comment]
Thank you, tbh this may indicate a bug in multi-emit in F# Interactive itself, I'll look into it.

**Comment by dsyme** [comment]
Bug recorded here: https://github.com/dotnet/fsharp/issues/12886

**Comment by nhirschey** [comment]
This issue about multi-emit warnings is fixed. I've confirmed in fsdocs version 17.3.0

![image](https://user-images.githubusercontent.com/5226115/223705931-38e43048-3095-4750-abca-8688273bf751.png)
