### ISSUE TITLE
Video content is not being served.

### ISSUE THREAD

**Issue by nojaf** [fsprojects/FSharp.Formatting#749]
Hello, 

I'm trying to include a video on a static HTML page.
The videos (*.mp4 and *.webm) are currently not playing and I believe that is because the mime types are not set by Suave.

https://github.com/fsprojects/FSharp.Formatting/blob/f389c0df2355412286b7a05a4aa86992f878b46d/src/fsdocs-tool/BuildCommand.fs#L630-L649

https://github.com/SuaveIO/suave/blob/57d69e39e67a5b1a1c60b7c015c698a1901a9420/src/Suave/Combinators.fs#L90-L114

The Suave docs explain how to add an additional mime type: https://suave.io/files.html

Can I include some more mime types? Hardcoded or via settings?

**Comment by nojaf** [comment]
I actually already have another one: `site.webmanifest`.
Something flexible using settings might be the way to go here.

**Comment by nojaf** [comment]
Hello @dsyme and 
@eiriktsarpalis, this issue was fixed in https://github.com/fsprojects/FSharp.Formatting/pull/752.
I've been using my local repository to start using this fix but someone else would be taking over that work. Could we have a release of this please?

**Comment by dsyme** [comment]
Yup. To make a release you can send a PR to release notes updating version and release should be automatic once merged

**Comment by dsyme** [comment]
Please let me know if this doesn't go though OK

https://github.com/fsprojects/FSharp.Formatting/actions/runs/2593557770

**Comment by nojaf** [comment]
This worked, many thanks @dsyme
