### ISSUE TITLE
Relative paths in html anchors

### ISSUE THREAD

**Issue by nojaf** [fsprojects/FSharp.Formatting#769]
Somewhat related to https://github.com/fsprojects/FSharp.Formatting/issues/764.
If the links are defined inside `<a>` tags in Markdown, they are not transformed to their `.html` counterparts.

We typically use:

```html
<div class="d-flex justify-content-between my-4">
  <a href="./GettingStarted.html">Previous</a>
  <a href="./Configuration.html">Next</a>
</div>
```

to get around this. 
Preferably we can write `<a href="./GettingStarted.md">Previous</a>` as well here.

**Comment by nojaf** [comment]
Initial guess, with some more processing in https://github.com/fsprojects/FSharp.Formatting/blob/688cc5c4cfe846677dff5809c2cd0911a48d077f/src/FSharp.Formatting.Markdown/MarkdownUtils.fs#L318

we can achieve this? If this is the case, would you accept a PR?

**Comment by dsyme** [comment]
That seems quite hard to arrange - it would mean parsing arbitrary HTML.

**Comment by dsyme** [comment]
That's reasonable, yes
