### ISSUE TITLE
FSharp.Formatting NuGet packages requires specific version of FSharp.Compiler.Service

### ISSUE THREAD

**Issue by object** [fsprojects/FSharp.Formatting#771]
Prior version 15.0.0 FSharp.Formatting NuGet package had a dependency on version of FSharp.Compiler.Service >= 40.0.0, so any higher version of FShapr.Compiler.Service fit. Newer versions of FSharp.Formatting require specific versions of FSharp.Compiler.Service, e.g.:

15.0.0 -> 41.0.3
15.0.1 -> 41.0.4
...
16.1.0 -> 41.0.5
16.1.1 -> 41.0.5

Is there a reason for such strict dependency? It complicates version resolution process and sometimes makes impossible to use latest versions of  core FSharp libraries.

**Comment by dsyme** [comment]
Hmmmm not sure.  It could be loosened. 

The problem is, FCS right now has no real binary compat promise, even between minor versions, so we may be exposed to breaking changes. It's somewhat unlikely given the parts of the FCS API we're using but it can happen.

**Comment by dsyme** [comment]
Which parts of which FSharp.Formatting packages are you using?

**Comment by object** [comment]
Not using directly, through one of the libraries. I will check tomorrow.

**Comment by object** [comment]
I checked our usage of the package, and in fact it's no longer in use in our solution, must be something we used in the past. Based on your explanation about risk of breaking changes, I am closing the issue.
