### ISSUE TITLE
Favicon not showing for API docs

### ISSUE THREAD

**Issue by brianrourkeboll** [fsprojects/FSharp.Formatting#773]
Should this

https://github.com/fsprojects/FSharp.Formatting/blob/d0ac84e3a39221cc536d34a57e3f0f9dfec0f2df/docs/_template.html#L16

instead be something like

```diff
- <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico"> 
+ <link rel="shortcut icon" type="image/x-icon" href="{{root}}img/favicon.ico"> 
```

?

Right now, the favicon shows for top-level files, but not for generated API docs under `/reference`. You can currently see this for the docs for this repo itself:

Compare https://fsprojects.github.io/FSharp.Formatting/ with favicon

![image](https://user-images.githubusercontent.com/14795984/194615659-3b5aedf3-fffb-4f23-85b3-78da673fd160.png)

But https://fsprojects.github.io/FSharp.Formatting/reference/index.html without

![image](https://user-images.githubusercontent.com/14795984/194615961-54f1c238-f494-4487-88b4-a2b83329826e.png)

When I make the change suggested above (prepending `{{root}}` to `img/favicon.ico` → `{{root}}img/favicon.ico`) to the template in one of my own projects, the favicon now works correctly for both top-level files and API docs.

**Comment by dsyme** [comment]
@brianrourkeboll Yes that looks right - can you submit a PR please to fix this? Thanks

**Comment by brianrourkeboll** [comment]
@dsyme #775.
