### ISSUE TITLE
Output markdown from variable

### ISSUE THREAD

**Issue by dburriss** [fsprojects/FSharp.Formatting#777]
I am trying to output the content of a variable as markdown.
As an example:
```fsharp
let content = someFunctionThatReturnsYamlString()
let md = $"
```yaml
{content}
```"
(*** include-value: md ***)
```

## Current

Then for documentation I can output styled yaml instead of a "string" as seen below.
![image](https://user-images.githubusercontent.com/5071495/200550777-596427de-e71c-4a26-ab65-e495a303031f.png)

If this is not possible, I am more than happy to try to pick it up as a feature if maintainers think it is worth adding. Maybe something like this:

## Desired (or similar)

```fsharp
let k8sOutput' = KubeCtlWriter.toYaml k8sConfig
(*** hide ***)
let md = $"
{k8sOutput'.content}
"
(*** include-markdown: md ***)
```

![image](https://user-images.githubusercontent.com/5071495/200552055-4fb0b224-8aea-4678-a3bb-d318b53055ab.png)

**Comment by nhirschey** [comment]
There is no yaml syntax highlighter (people have proposed adding support for things like highlight.js, but it isn't added yet).

Not sure if this is close to what you want, but here's some relatively simple options below. If this doesn't work, you could look more at the embedding output examples [here](https://fsprojects.github.io/FSharp.Formatting/evaluation.html#F-Formatting-as-a-Library-Specifying-the-Evaluator-and-Formatting), which show how to make a custom formatter.

![image](https://user-images.githubusercontent.com/5226115/201244128-41a5801d-731d-4b91-8aa3-4ab240cd0ae8.png)
code:

```fsharp
(**
Some markdown text
*)

(***hide***)
let md = "
apiVersion: apps/v1
kind: Deployment
"
printfn "%s" md
(***include-output ***)

(***hide***)
let makeMd text = $"""
<pre class="fssnip highlighted">
    <code lang="fsharp">
    {text}
    </code>
</pre>
"""

makeMd md
(***include-it-raw***)

(**
Some more text

    [yaml]
    apiVersion: apps/v1
    kind: Deployment
*)
```

**Comment by dburriss** [comment]
Thanks @nhirschey I reckon this will get me what I want.
