### ISSUE TITLE
Setting root for links generated by fsdocs

### ISSUE THREAD

**Issue by davedawkins** [fsprojects/FSharp.Formatting#785]
This is how I'm doing it now, to test locally:
```xml
    <PackageProjectUrl>..</PackageProjectUrl>
    <!-- <PackageProjectUrl>https://github.com/DaveDawkins/Sutil</PackageProjectUrl> -->
```

in order to have `root` set as shown here
```
Substitutions/parameters:
  root --> ../
  fsdocs-authors --> David Dawkins
  fsdocs-collection-name --> Sutil
  fsdocs-collection-name-link --> ../
```

Is there  a better way? (reading the source suggests that it will derive `root` from `<PackageProjectUrl>` only

Thank you!

**Comment by nhirschey** [comment]
You can specify parameters at the [command line](https://fsprojects.github.io/FSharp.Formatting/commandline.html).

```
dotnet fsdocs build --parameters root ../
```

```
Substitutions/parameters:
  root --> ../
```

**Comment by davedawkins** [comment]
That is useful to know, thank you. Just to make sure I'm not msising anything, does it mention `root` in that page there, or how to rebase links? If not, then I can submit a doc PR

**Comment by davedawkins** [comment]
Tested, that works - thanks again

**Comment by nhirschey** [comment]
It's there but not super explicit and there's no examples. It could probably be improved. At the bottom of the [templates and substutions](https://fsprojects.github.io/FSharp.Formatting/content.html#Templates-and-Substitutions) section that you were referencing it mentions

> For the fsdocs tool, additional substitutions can be specified using --parameters.

The command line tool --help output does a better job documenting it, showing the "--parameters key value" format.
