### ISSUE TITLE
[omit] vs <exclude/>

### ISSUE THREAD

**Issue by davedawkins** [fsprojects/FSharp.Formatting#786]
```sh
% dotnet fsdocs --version
fsdocs 16.1.1
% dotnet --version
6.0.404
```
Both `[omit]` and `<exclude>` are mentioned in the [documentation](https://fsprojects.github.io/FSharp.Formatting/apidocs.html).

However:
- `<exclude>` doesn't appear to work (neither does `<exclude/>`)
- `[omit]` *does* work, but:
  - it produces a warning
  - sometimes it doesn't and becomes the summary for the item being excluded. 

The warning (which gives a good example of how to use `<exclude/>`:
```sh
The use of `[omit]` and other commands in XML comments is deprecated, please use XML extensions, see https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1031-xmldoc-extensions.md
```

When `[omit]` doesn't work:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/285421/211220460-4a0c908e-2b98-4c29-b845-3e0f219abe02.png">

**Comment by davedawkins** [comment]
For reference, BindHelpers is an internal module. Eg
```fs
[<AutoOpen>]
module Sutil.Bindings

///[omit]
[<AutoOpen>]
module BindHelpers =
    // ..
```

**Comment by davedawkins** [comment]
Verified that it doesn't work in 17.2 either
```
% dotnet --version
7.0.101
% dotnet fsdocs --version
fsdocs 17.2.0
```

I have tried:
```
///<exclude>
/// <exclude>
///<exclude/>
/// <exclude/>
/// <exclude> </exclude>
/// <exclude value="true">true</exclude>
```

From your link:
```fs
        for e in doc.Elements(XName.Get "exclude") do
            cmds.["exclude"] <- e.Value

        for e in doc.Elements(XName.Get "omit") do
            cmds.["omit"] <- e.Value
```

My guess is that either:
- `exclude` isn't being parsed into `doc.Elements` or
- `e.Value` isn't set correctly for `<exclude/>` or
- `cmds ["exclude"]` is being ignored somewhere

If you're a maintainer, could you point me at the code that assigns/parses/builds `doc.Elements` please?

**Comment by davedawkins** [comment]
I'm writing a test for `<exclude/>` and `[omit]`

**Comment by nojaf** [comment]
I can't really say I know anything more than you do at this point.
I found a `let doc = XDocument.Load(xmlFile)` call in that same file, so interestingly enough it is grabbing the XML from a separate file and something embedded in the assembly, I guess.
Or not, I honestly don't know and won't be of much use here.
Good luck!

**Comment by davedawkins** [comment]
OK :-) Well, I'm down the rabbit hole now - I'll keep at it. I don't have a lot of success with fsdocs.

**Comment by nojaf** [comment]
Thank you!

**Comment by davedawkins** [comment]
OK, so part of the problem is that
```fs
/// A comment
/// <exclude/>
```
is parsed as

```xml
<summary>A comment&lt;exclude/&gt</summary>
```

This means a workaround is to explicitly tag the comment
```fs
/// <summary>
/// A comment
/// </summary>
/// <exclude/>
```

**Comment by davedawkins** [comment]
Nested modules are still included though.

**Comment by davedawkins** [comment]
Fixed it. PR incoming

**Comment by nhirschey** [comment]
Closed by https://github.com/fsprojects/FSharp.Formatting/pull/787
