### ISSUE TITLE
Clicking on github link leads to 404

### ISSUE THREAD

**Issue by davedawkins** [fsprojects/FSharp.Formatting#788]
Clicking on 

![image](https://user-images.githubusercontent.com/285421/212479369-83398cb6-0a28-4894-aa83-47d7fe064e92.png)

with href
```
https://github.com/davedawkins/Sutil/src/Sutil/DOM.fs#L1217-1217
```

leads to `Not Found`.

A link that does work is

```
https://github.com/davedawkins/Sutil/blob/main/src/Sutil/DOM.fs#L1217-1217
```

The difference is the `blob/main/` insert. How did I fix this, please?

**Comment by davedawkins** [comment]
The github link icon in context:
![image](https://user-images.githubusercontent.com/285421/212479426-ca85a415-27b9-4a9e-ae61-a71a07356a6d.png)

**Comment by nhirschey** [comment]
The properties for this repo come from [Directory.Build.props](https://github.com/fsprojects/FSharp.Formatting/blob/main/Directory.Build.props). It's what I've followed.

Looking at the Sutil .fsproj, you don't have `<RepositoryType>git</RepositoryType>`. Does adding that fix it?

If that's the fix then we should add it to the [styling docs](https://fsprojects.github.io/FSharp.Formatting/styling.html#Customizing-via-Styling-Parameters).

**Comment by davedawkins** [comment]
YES! That fixed it. Thank you!

**Comment by baronfel** [comment]
Just a note that if you add [Sourcelink](https://GitHub.com/dotnet/sourcelink) to your repo then these properties are set for free. My favorite way of doing this is adding the Dotnet.ReproducibleBuilds package, it handles all of the configuration automatically. This also makes editor tooling like f12 actually navigate to your source code.
