### ISSUE TITLE
String Links 404

### ISSUE THREAD

**Issue by felix-alonso** [fsprojects/FSharp.Formatting#794]
The links to [System.String](http://msdn2.microsoft.com/en-us/library/system.string.aspx) and [System.Text.RegularExpressions](http://msdn2.microsoft.com/library/system.text.regularexpressions.aspx) are 404'ing on this page:

https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-stringmodule.html

Seems like the format of the link changed:

https://learn.microsoft.com/en-us/dotnet/api/system.string?view=netcore-3.1

**Comment by baronfel** [comment]
it looks like this has (partially) already been fixed in FSharp.Formatting - the URL generation uses docs.microsoft.com: https://github.dev/fsprojects/FSharp.Formatting/blob/a9ecebc3db319f2a3d07f841755ffc61bbf936df/src/FSharp.Formatting.ApiDocs/GenerateModel.fs#L950.

However, this should be updated to use `learn.microsoft.com` instead as a root.

Separately, the https://github.com/fsharp/fsharp-core-docs repo should update to a more recent FSharp.Formatting and republish the docs to get the fix.

**Comment by nojaf** [comment]
Hi Felix, are you interested in contributing here?

**Comment by felix-alonso** [comment]
@nojaf,

Possibly! I'm just getting started with F#. How could I help?

**Comment by felix-alonso** [comment]
I think I've gotten past the build issue. I can run the documentation locally. I'm just not sure how I can verify that I've fixed the external documentation link.

I see that this `Classic XML Doc Comments` contains an external link, but it uses the other URL format. When I click on the link it redirects to the new URL format

Current: `https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/`
Redirect: `https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/`

![image](https://user-images.githubusercontent.com/11393098/219884217-03654d82-6fe3-4291-acbb-b68a61cf984d.png)

When I look through the project it seems like there are half a dozen other references to that URL.

![image](https://user-images.githubusercontent.com/11393098/219884163-750ec8e9-1826-41b8-9ffb-aeb6e532b1a3.png)

Should change all of the instances of `docs.microsoft.com/` to `learn.microsoft.com/`?

**Comment by nhirschey** [comment]
Thanks for the help!

> I'm just not sure how I can verify that I've fixed the external documentation link.

The fsharp core docs are here https://github.com/fsharp/fsharp-core-docs

You’d want to build that repo’s docs using the fsdocs tool built with your PR. You can build those docs following the [Build Steps](https://github.com/fsharp/fsharp-core-docs) on the readme.

The key thing would be to clone the repos as described in the fsharp-core-docs build steps. Then make your proposed changes in the FSharp.Formatting repo and build fsdocs. Then do 

```
(from 'fsharp-core-docs')
FSharp.Formatting\src\FSharp.Formatting.CommandTool\bin\Release\netcoreapp3.1\fsdocs.exe watch --sourcefolder fsharp
```

**Comment by felix-alonso** [comment]
@nhirschey,

I've been able to mostly follow the build steps. I had to run the following to spin up the website:

```
(start in 'fsharp-core-docs')
dotnet restore FSharp.Core

(make 'fsharp-core-docs/fsharp' and 'fsharp-core-docs/FSharp.Formatting' )
git clone https://github.com/dotnet/fsharp --depth 1 -b main
git clone https://github.com/fsprojects/FSharp.Formatting --depth 1

(build 'fsharp-core-docs/fsharp'; didn't take noVisualStudio flag)
pushd fsharp
./build.sh
popd

(build 'fsharp-core-docs/FSharp.Formatting'; didn't take build flag)
pushd FSharp.Formatting
./build.sh
popd

(from 'fsharp-core-docs')
FSharp.Formatting/src/fsdocs-tool/bin/Release/net7.0/fsdocs watch --sourcefolder fsharp
```

However, it doesn't seem to pick up any modules in fsharp project. See the docs below:

![image](https://user-images.githubusercontent.com/11393098/219902177-30e4a797-9a64-4b6b-a55f-bc67cc2e60a0.png)

Similarly, clicking on any of the documentation links it just complains that the connection was reset:

![image](https://user-images.githubusercontent.com/11393098/219902397-1a570ecd-ef68-4840-8e2e-22c4dd6fe7c2.png)

![image](https://user-images.githubusercontent.com/11393098/219902307-277cb7fc-1b50-42d9-82b3-d63911e30600.png)

 Any clue what might be causing this?

**Comment by nojaf** [comment]
Hello @felix-alonso, I just tried these steps on Windows and could view the API docs there.
So, maybe this wasn't designed to work on anything else than Windows. The [workflows](https://github.com/nojaf/fsharp-core-docs/tree/main/.github/workflows) seem to support this theory.
I can help you with the `fsharp-core-docs` repository once the fix is available in fsdocs.

> Should change all of the instances of docs.microsoft.com/ to learn.microsoft.com/?

Yes, I believe so, if possible maybe refactor things a bit so that we use `"learn.microsoft.com/"` as a single constant.

Thanks again for looking into this!

**Comment by nojaf** [comment]
I just found out that the links to [System.String](http://msdn2.microsoft.com/en-us/library/system.string.aspx) and [System.Text.RegularExpressions](http://msdn2.microsoft.com/library/system.text.regularexpressions.aspx) are actually coming from:

https://github.com/dotnet/fsharp/blob/979fa51c3440c3e32b56c579b030b9df5636f9f1/src/FSharp.Core/string.fsi#L10-L11

So, this would need a fix in `dotnet/fsharp` as well.

**Comment by felix-alonso** [comment]
@nojaf,

I've marked this PR as ready for review. Thank you for your guidance in this process!

https://github.com/fsprojects/FSharp.Formatting/pull/797

**Comment by felix-alonso** [comment]
> I just found out that the links to [System.String](http://msdn2.microsoft.com/en-us/library/system.string.aspx) and [System.Text.RegularExpressions](http://msdn2.microsoft.com/library/system.text.regularexpressions.aspx) are actually coming from:
> 
> https://github.com/dotnet/fsharp/blob/979fa51c3440c3e32b56c579b030b9df5636f9f1/src/FSharp.Core/string.fsi#L10-L11
> 
> So, this would need a fix in `dotnet/fsharp` as well.

Looks like these are the correct links:

- System.String
  - Before: `http://msdn2.microsoft.com/en-us/library/system.string.aspx`
  - After: `https://learn.microsoft.com/en-us/dotnet/api/system.string`
- System.Text.RegularExpressions
  - Before: `http://msdn2.microsoft.com/library/system.text.regularexpressions.aspx`
  - After: `https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions`

So the change is something like `s|msdn2.microsoft.com/en-us/library|learn.microsoft.com/en-us/dotnet/api|g`.

**Comment by nojaf** [comment]
@felix-alonso thanks! I've updated all the links at the compiler side: https://github.com/dotnet/fsharp/pull/14774
Once, that is merged we can try and update https://github.com/fsharp/fsharp-core-docs

**Comment by felix-alonso** [comment]
@nojaf,

Does this mean I get to put FSharp core contributor on my resume? :rofl:  

Thank you!

**Comment by nojaf** [comment]
@felix-alonso I believe this problem is resolved now. Please confirm.

**Comment by felix-alonso** [comment]
@nojaf,

It's looking good! Thank you so much!

**Comment by nojaf** [comment]
Thanks for confirming.
