### ISSUE TITLE
Missing `fsdocs-page-source` in ApiDocs generation

### ISSUE THREAD

**Issue by TheAngryByrd** [fsprojects/FSharp.Formatting#805]
I'm adding a "Edit this page" type link to my `_template.html`

```html
href="{{fsdocs-repository-link}}edit/{{fsdocs-repository-branch}}/{{fsdocs-page-source}}"
```

Which works for `md/fsx` files but it doesn't work for the API Documentation generation.

It seems to be part of the [substitutions in Literate Programming](https://github.com/fsprojects/FSharp.Formatting/blob/e665aa95ab897e5e2c543e5847f3820b3e215e92/src/FSharp.Formatting.Literate/Formatting.fs#L171) but it seems missing from [ApiDocs](https://github.com/fsprojects/FSharp.Formatting/blob/e665aa95ab897e5e2c543e5847f3820b3e215e92/src/FSharp.Formatting.ApiDocs/GenerateHtml.fs#L657-L664) side.  

Is there any reason it shouldn't be part of substitutions for the ApiDocs?

**Comment by nojaf** [comment]
Hi there, this kinda makes sense I think.
As the documentation is generated, some pages wouldn't really have a source file to go to.
For example https://fsprojects.github.io/fantomas/reference/fantomas-core.html
This really just bundles everything it found in the processed assembly.
There is no physical file to go there.

**Comment by TheAngryByrd** [comment]
Ah yeah good point. 

Hmm, I guess then best way to hide it is to have some client side js if it’s not a valid link. I know you can have a template for references but I don’t want to keep them in sync for 1 button difference.
