### ISSUE TITLE
Need to update repo's nuget API key

### ISSUE THREAD

**Issue by nhirschey** [fsprojects/FSharp.Formatting#830]
Hi @dsyme, the FSharp.Formatting repo's nuget API key has expired so we cannot push new versions to nuget. No rush, but can you update the repo's nuget API key environment variable when you get a chance? Thanks.

Failed workflow:
https://github.com/fsprojects/FSharp.Formatting/actions/runs/5275827431/job/14280597027

error:
```cmd
dotnet nuget push "artifacts/*.nupkg" -s https://api.nuget.org/v3/index.json -k *** --skip-duplicate
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_ROOT: /usr/share/dotnet
Pushing FSharp.Formatting.Literate.18.1.1.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 579ms
error: Response status code does not indicate success: 40[3](https://github.com/fsprojects/FSharp.Formatting/actions/runs/5275827431/job/14280597027#step:6:3) (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
```

**Comment by dsyme** [comment]
I've updated the key, can you check? 

It lasts for one year. As a note - the packages in this repo are write access to myself and [fsprojects](https://www.nuget.org/profiles/fsprojects) org-account on nuget.   I willwork to make sure one other admin - most likely @sergey-tihon - also has access to fsprojects nuget org account.

**Comment by nhirschey** [comment]
It works, the publish workflow ran and pushed version 18.1.1 to nuget. Thanks!
