### ISSUE TITLE
Output font size on mobile safari is too big

### ISSUE THREAD

**Issue by nhirschey** [fsprojects/FSharp.Formatting#889]
Maybe my phone is weird, but I’m not seeing raw fsi output scaling correctly in docs. See screenshot from the csv provider below. The green “HLOC” output text font size is too big compared to the body text and fsharp code block. 

I cannot reproduce this with small window sizes desktop edge browser, but I consistently get it with my iPhone. 

![image](https://github.com/fsprojects/FSharp.Formatting/assets/5226115/aa0dcdbc-3444-4e7e-949b-188e9016b428)

**Comment by nhirschey** [comment]
Thanks @nojaf 
https://fsprojects.github.io/FSharp.Data/library/CsvProvider.html

It seems to happen when the output is bigger than the window. Also see my teaching site [here](https://nhirschey.github.io/Teaching/fundamentals.html#Tuples). Simple tuple output like ‘ val it: int * int = (1, 2)’ is formatted correctly but if you scroll down fsi output for ‘simpleReturnTuple’ is too big.

**Comment by nhirschey** [comment]
Another example in compiler docs release notes, the snippet font size on this page is all too big

https://fsharp.github.io/fsharp-compiler-docs/release-notes/About.html

**Comment by nojaf** [comment]
Thanks, the problem here is that I need to see this in Safari to be able to address it.
I should try and have a screen sharing session with someone that has a Mac. I can't reproduce this in the Chrome emulator, so I believe the problem is a browser styling default that we still need to override.

**Comment by nojaf** [comment]
Hi @nhirschey, could you try https://www.nuget.org/packages/FSharp.Formatting/20.0.0-alpha-017 on your personal website? It might improve things.

**Comment by nhirschey** [comment]
Hi @nojaf, thanks for giving this a shot. I upgraded to alpha 17 but the problem is still there unfortunately.
