### ISSUE TITLE
Making a change to a file under `docs` doesn't regenerate the output

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/FSharp.Formatting#937]
I have a folder `docs` with `index.md` and `test/page1.md` in it.

When running `dotnet fsdocs watch` and then making a change to either of these files nothing happens.

I would expect F# Formatting to regenerate the output for the changed file and update the browser content. This is what is documented at https://fsprojects.github.io/FSharp.Formatting/commandline.html#The-watch-command

I am using `fsdocs 20.0.1+56b856bc3be5ab7ff7c1bbcb30fe0f3e758235cc`

**Comment by nojaf** [comment]
Yeah, this rings a bell. Did you add the files after running the watch command?

**Comment by MangelMaxime** [comment]
Adding them before or after makes no changes for me.

I even deleted the cache folder in case but it didn't change things.

Something else, that seems strange is that even if I manually change the generated file it is not reflected in the browser after reloading the page. (This one is probably due to a separate issue perhaps a caching issue in Suave or in the browser).

**Comment by nojaf** [comment]
Just tried this in Windows, I cannot reproduce this problem at all.

**Comment by MangelMaxime** [comment]
After a restart of my machine I can't reproduce anymore.

Perhaps it didn't like being on sleep for 2 weeks 😅

Sorry about that

**Comment by nojaf** [comment]
No worries, happy it was false alarm. And there are situations where refresh doesn't properly work, so I'm glad at least the happy path works.
