### ISSUE TITLE
`build.fsx` clean up and enhancements

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/FSharp.Formatting#938]
Hello,

while working on "my PR" I needed to add a new `pipeline` to simplify testing the output of the API Docs generations using a test project.

While doing so I saw that some variables are not used in the `build.fsx`:

```fs
// Information about the project to be used at NuGet and in AssemblyInfo files
let project = "FSharp.Formatting"

let summary =
    "A package of libraries for building great F# documentation, samples and blogs"

let license = "Apache 2.0 License"
```

Are you ok if I send a PR to delete dead code?

For my pipeline addition, I need to work with "complex path" and lengthy CLI. Would you be ok if I was to introduce the 2 packages below?

- [EasyBuild.FileSystemProvider](https://github.com/easybuild-org/EasyBuild.FileSystemProvider) for dealing with the paths in a type safe manner
- [BlackFox.CommandLine](https://github.com/vbfox/FoxSharp/tree/master/src/BlackFox.CommandLine) for making building CLI string easier

I used these projects extensively for a while now and it simplified a lot my build script experience while making maintenance easier.

I can create a separate PR to showcase how it would look like.

**Comment by nojaf** [comment]
Hi,

> I needed to add a new pipeline

I want to push back on that a little. Once we merge, it's on us to maintain, so we need to be sure it's necessary. Is this really something that needs to be part of the repository? Without more context, it feels like this might be more about your preferred workflow than a true necessity.

> Are you ok if I send a PR to delete dead code?

Sure, go ahead.

> Would you be ok if I was to introduce the 2 packages below?

My initial reaction is no. Adding new dependencies can lead to issues down the line, especially with dotnet. Things tend to break over time, so we should be cautious about introducing anything new unless it's absolutely necessary.

**Comment by MangelMaxime** [comment]
> My initial reaction is no. Adding new dependencies can lead to issues down the line, especially with dotnet. Things tend to break over time, so we should be cautious about introducing anything new unless it's absolutely necessary.

As you wish, I think that working with string interpolation for CLI is harder to maintain because you need to escape arguments and things like that.

> I want to push back on that a little. Once we merge, it's on us to maintain, so we need to be sure it's necessary. Is this really something that needs to be part of the repository? Without more context, it feels like this might be more about your preferred workflow than a true necessity.

The needs will be explained in the signature-like PR because it is related to that enhancement.
